package com.ojp.entity;

public class DisAdministrators {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.a_id
     *
     * @mbg.generated
     */
    private String aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.a_name
     *
     * @mbg.generated
     */
    private String aName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.a_sex
     *
     * @mbg.generated
     */
    private Integer aSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.u_number
     *
     * @mbg.generated
     */
    private String uNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.a_state
     *
     * @mbg.generated
     */
    private Integer aState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.a_thedis_city
     *
     * @mbg.generated
     */
    private String aThedisCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.a_adress
     *
     * @mbg.generated
     */
    private String aAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.a_pwd
     *
     * @mbg.generated
     */
    private String aPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.a_phone
     *
     * @mbg.generated
     */
    private String aPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_administrators.a_remarks
     *
     * @mbg.generated
     */
    private String aRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.a_id
     *
     * @return the value of dis_administrators.a_id
     *
     * @mbg.generated
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.a_id
     *
     * @param aId the value for dis_administrators.a_id
     *
     * @mbg.generated
     */
    public void setaId(String aId) {
        this.aId = aId == null ? null : aId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.a_name
     *
     * @return the value of dis_administrators.a_name
     *
     * @mbg.generated
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.a_name
     *
     * @param aName the value for dis_administrators.a_name
     *
     * @mbg.generated
     */
    public void setaName(String aName) {
        this.aName = aName == null ? null : aName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.a_sex
     *
     * @return the value of dis_administrators.a_sex
     *
     * @mbg.generated
     */
    public Integer getaSex() {
        return aSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.a_sex
     *
     * @param aSex the value for dis_administrators.a_sex
     *
     * @mbg.generated
     */
    public void setaSex(Integer aSex) {
        this.aSex = aSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.u_number
     *
     * @return the value of dis_administrators.u_number
     *
     * @mbg.generated
     */
    public String getuNumber() {
        return uNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.u_number
     *
     * @param uNumber the value for dis_administrators.u_number
     *
     * @mbg.generated
     */
    public void setuNumber(String uNumber) {
        this.uNumber = uNumber == null ? null : uNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.a_state
     *
     * @return the value of dis_administrators.a_state
     *
     * @mbg.generated
     */
    public Integer getaState() {
        return aState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.a_state
     *
     * @param aState the value for dis_administrators.a_state
     *
     * @mbg.generated
     */
    public void setaState(Integer aState) {
        this.aState = aState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.a_thedis_city
     *
     * @return the value of dis_administrators.a_thedis_city
     *
     * @mbg.generated
     */
    public String getaThedisCity() {
        return aThedisCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.a_thedis_city
     *
     * @param aThedisCity the value for dis_administrators.a_thedis_city
     *
     * @mbg.generated
     */
    public void setaThedisCity(String aThedisCity) {
        this.aThedisCity = aThedisCity == null ? null : aThedisCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.a_adress
     *
     * @return the value of dis_administrators.a_adress
     *
     * @mbg.generated
     */
    public String getaAdress() {
        return aAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.a_adress
     *
     * @param aAdress the value for dis_administrators.a_adress
     *
     * @mbg.generated
     */
    public void setaAdress(String aAdress) {
        this.aAdress = aAdress == null ? null : aAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.a_pwd
     *
     * @return the value of dis_administrators.a_pwd
     *
     * @mbg.generated
     */
    public String getaPwd() {
        return aPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.a_pwd
     *
     * @param aPwd the value for dis_administrators.a_pwd
     *
     * @mbg.generated
     */
    public void setaPwd(String aPwd) {
        this.aPwd = aPwd == null ? null : aPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.a_phone
     *
     * @return the value of dis_administrators.a_phone
     *
     * @mbg.generated
     */
    public String getaPhone() {
        return aPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.a_phone
     *
     * @param aPhone the value for dis_administrators.a_phone
     *
     * @mbg.generated
     */
    public void setaPhone(String aPhone) {
        this.aPhone = aPhone == null ? null : aPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_administrators.a_remarks
     *
     * @return the value of dis_administrators.a_remarks
     *
     * @mbg.generated
     */
    public String getaRemarks() {
        return aRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_administrators.a_remarks
     *
     * @param aRemarks the value for dis_administrators.a_remarks
     *
     * @mbg.generated
     */
    public void setaRemarks(String aRemarks) {
        this.aRemarks = aRemarks == null ? null : aRemarks.trim();
    }
}