package com.ojp.entity;

import java.util.ArrayList;
import java.util.List;

public class DisAdministratorsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public DisAdministratorsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAIdIsNull() {
            addCriterion("a_id is null");
            return (Criteria) this;
        }

        public Criteria andAIdIsNotNull() {
            addCriterion("a_id is not null");
            return (Criteria) this;
        }

        public Criteria andAIdEqualTo(String value) {
            addCriterion("a_id =", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotEqualTo(String value) {
            addCriterion("a_id <>", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThan(String value) {
            addCriterion("a_id >", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThanOrEqualTo(String value) {
            addCriterion("a_id >=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThan(String value) {
            addCriterion("a_id <", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThanOrEqualTo(String value) {
            addCriterion("a_id <=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLike(String value) {
            addCriterion("a_id like", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotLike(String value) {
            addCriterion("a_id not like", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdIn(List<String> values) {
            addCriterion("a_id in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotIn(List<String> values) {
            addCriterion("a_id not in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdBetween(String value1, String value2) {
            addCriterion("a_id between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotBetween(String value1, String value2) {
            addCriterion("a_id not between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andANameIsNull() {
            addCriterion("a_name is null");
            return (Criteria) this;
        }

        public Criteria andANameIsNotNull() {
            addCriterion("a_name is not null");
            return (Criteria) this;
        }

        public Criteria andANameEqualTo(String value) {
            addCriterion("a_name =", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotEqualTo(String value) {
            addCriterion("a_name <>", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameGreaterThan(String value) {
            addCriterion("a_name >", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameGreaterThanOrEqualTo(String value) {
            addCriterion("a_name >=", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameLessThan(String value) {
            addCriterion("a_name <", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameLessThanOrEqualTo(String value) {
            addCriterion("a_name <=", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameLike(String value) {
            addCriterion("a_name like", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotLike(String value) {
            addCriterion("a_name not like", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameIn(List<String> values) {
            addCriterion("a_name in", values, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotIn(List<String> values) {
            addCriterion("a_name not in", values, "aName");
            return (Criteria) this;
        }

        public Criteria andANameBetween(String value1, String value2) {
            addCriterion("a_name between", value1, value2, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotBetween(String value1, String value2) {
            addCriterion("a_name not between", value1, value2, "aName");
            return (Criteria) this;
        }

        public Criteria andASexIsNull() {
            addCriterion("a_sex is null");
            return (Criteria) this;
        }

        public Criteria andASexIsNotNull() {
            addCriterion("a_sex is not null");
            return (Criteria) this;
        }

        public Criteria andASexEqualTo(Integer value) {
            addCriterion("a_sex =", value, "aSex");
            return (Criteria) this;
        }

        public Criteria andASexNotEqualTo(Integer value) {
            addCriterion("a_sex <>", value, "aSex");
            return (Criteria) this;
        }

        public Criteria andASexGreaterThan(Integer value) {
            addCriterion("a_sex >", value, "aSex");
            return (Criteria) this;
        }

        public Criteria andASexGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_sex >=", value, "aSex");
            return (Criteria) this;
        }

        public Criteria andASexLessThan(Integer value) {
            addCriterion("a_sex <", value, "aSex");
            return (Criteria) this;
        }

        public Criteria andASexLessThanOrEqualTo(Integer value) {
            addCriterion("a_sex <=", value, "aSex");
            return (Criteria) this;
        }

        public Criteria andASexIn(List<Integer> values) {
            addCriterion("a_sex in", values, "aSex");
            return (Criteria) this;
        }

        public Criteria andASexNotIn(List<Integer> values) {
            addCriterion("a_sex not in", values, "aSex");
            return (Criteria) this;
        }

        public Criteria andASexBetween(Integer value1, Integer value2) {
            addCriterion("a_sex between", value1, value2, "aSex");
            return (Criteria) this;
        }

        public Criteria andASexNotBetween(Integer value1, Integer value2) {
            addCriterion("a_sex not between", value1, value2, "aSex");
            return (Criteria) this;
        }

        public Criteria andUNumberIsNull() {
            addCriterion("u_number is null");
            return (Criteria) this;
        }

        public Criteria andUNumberIsNotNull() {
            addCriterion("u_number is not null");
            return (Criteria) this;
        }

        public Criteria andUNumberEqualTo(String value) {
            addCriterion("u_number =", value, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberNotEqualTo(String value) {
            addCriterion("u_number <>", value, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberGreaterThan(String value) {
            addCriterion("u_number >", value, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberGreaterThanOrEqualTo(String value) {
            addCriterion("u_number >=", value, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberLessThan(String value) {
            addCriterion("u_number <", value, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberLessThanOrEqualTo(String value) {
            addCriterion("u_number <=", value, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberLike(String value) {
            addCriterion("u_number like", value, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberNotLike(String value) {
            addCriterion("u_number not like", value, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberIn(List<String> values) {
            addCriterion("u_number in", values, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberNotIn(List<String> values) {
            addCriterion("u_number not in", values, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberBetween(String value1, String value2) {
            addCriterion("u_number between", value1, value2, "uNumber");
            return (Criteria) this;
        }

        public Criteria andUNumberNotBetween(String value1, String value2) {
            addCriterion("u_number not between", value1, value2, "uNumber");
            return (Criteria) this;
        }

        public Criteria andAStateIsNull() {
            addCriterion("a_state is null");
            return (Criteria) this;
        }

        public Criteria andAStateIsNotNull() {
            addCriterion("a_state is not null");
            return (Criteria) this;
        }

        public Criteria andAStateEqualTo(Integer value) {
            addCriterion("a_state =", value, "aState");
            return (Criteria) this;
        }

        public Criteria andAStateNotEqualTo(Integer value) {
            addCriterion("a_state <>", value, "aState");
            return (Criteria) this;
        }

        public Criteria andAStateGreaterThan(Integer value) {
            addCriterion("a_state >", value, "aState");
            return (Criteria) this;
        }

        public Criteria andAStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_state >=", value, "aState");
            return (Criteria) this;
        }

        public Criteria andAStateLessThan(Integer value) {
            addCriterion("a_state <", value, "aState");
            return (Criteria) this;
        }

        public Criteria andAStateLessThanOrEqualTo(Integer value) {
            addCriterion("a_state <=", value, "aState");
            return (Criteria) this;
        }

        public Criteria andAStateIn(List<Integer> values) {
            addCriterion("a_state in", values, "aState");
            return (Criteria) this;
        }

        public Criteria andAStateNotIn(List<Integer> values) {
            addCriterion("a_state not in", values, "aState");
            return (Criteria) this;
        }

        public Criteria andAStateBetween(Integer value1, Integer value2) {
            addCriterion("a_state between", value1, value2, "aState");
            return (Criteria) this;
        }

        public Criteria andAStateNotBetween(Integer value1, Integer value2) {
            addCriterion("a_state not between", value1, value2, "aState");
            return (Criteria) this;
        }

        public Criteria andAThedisCityIsNull() {
            addCriterion("a_thedis_city is null");
            return (Criteria) this;
        }

        public Criteria andAThedisCityIsNotNull() {
            addCriterion("a_thedis_city is not null");
            return (Criteria) this;
        }

        public Criteria andAThedisCityEqualTo(String value) {
            addCriterion("a_thedis_city =", value, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityNotEqualTo(String value) {
            addCriterion("a_thedis_city <>", value, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityGreaterThan(String value) {
            addCriterion("a_thedis_city >", value, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityGreaterThanOrEqualTo(String value) {
            addCriterion("a_thedis_city >=", value, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityLessThan(String value) {
            addCriterion("a_thedis_city <", value, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityLessThanOrEqualTo(String value) {
            addCriterion("a_thedis_city <=", value, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityLike(String value) {
            addCriterion("a_thedis_city like", value, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityNotLike(String value) {
            addCriterion("a_thedis_city not like", value, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityIn(List<String> values) {
            addCriterion("a_thedis_city in", values, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityNotIn(List<String> values) {
            addCriterion("a_thedis_city not in", values, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityBetween(String value1, String value2) {
            addCriterion("a_thedis_city between", value1, value2, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAThedisCityNotBetween(String value1, String value2) {
            addCriterion("a_thedis_city not between", value1, value2, "aThedisCity");
            return (Criteria) this;
        }

        public Criteria andAAdressIsNull() {
            addCriterion("a_adress is null");
            return (Criteria) this;
        }

        public Criteria andAAdressIsNotNull() {
            addCriterion("a_adress is not null");
            return (Criteria) this;
        }

        public Criteria andAAdressEqualTo(String value) {
            addCriterion("a_adress =", value, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressNotEqualTo(String value) {
            addCriterion("a_adress <>", value, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressGreaterThan(String value) {
            addCriterion("a_adress >", value, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressGreaterThanOrEqualTo(String value) {
            addCriterion("a_adress >=", value, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressLessThan(String value) {
            addCriterion("a_adress <", value, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressLessThanOrEqualTo(String value) {
            addCriterion("a_adress <=", value, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressLike(String value) {
            addCriterion("a_adress like", value, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressNotLike(String value) {
            addCriterion("a_adress not like", value, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressIn(List<String> values) {
            addCriterion("a_adress in", values, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressNotIn(List<String> values) {
            addCriterion("a_adress not in", values, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressBetween(String value1, String value2) {
            addCriterion("a_adress between", value1, value2, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAAdressNotBetween(String value1, String value2) {
            addCriterion("a_adress not between", value1, value2, "aAdress");
            return (Criteria) this;
        }

        public Criteria andAPwdIsNull() {
            addCriterion("a_pwd is null");
            return (Criteria) this;
        }

        public Criteria andAPwdIsNotNull() {
            addCriterion("a_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andAPwdEqualTo(String value) {
            addCriterion("a_pwd =", value, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdNotEqualTo(String value) {
            addCriterion("a_pwd <>", value, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdGreaterThan(String value) {
            addCriterion("a_pwd >", value, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdGreaterThanOrEqualTo(String value) {
            addCriterion("a_pwd >=", value, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdLessThan(String value) {
            addCriterion("a_pwd <", value, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdLessThanOrEqualTo(String value) {
            addCriterion("a_pwd <=", value, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdLike(String value) {
            addCriterion("a_pwd like", value, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdNotLike(String value) {
            addCriterion("a_pwd not like", value, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdIn(List<String> values) {
            addCriterion("a_pwd in", values, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdNotIn(List<String> values) {
            addCriterion("a_pwd not in", values, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdBetween(String value1, String value2) {
            addCriterion("a_pwd between", value1, value2, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPwdNotBetween(String value1, String value2) {
            addCriterion("a_pwd not between", value1, value2, "aPwd");
            return (Criteria) this;
        }

        public Criteria andAPhoneIsNull() {
            addCriterion("a_phone is null");
            return (Criteria) this;
        }

        public Criteria andAPhoneIsNotNull() {
            addCriterion("a_phone is not null");
            return (Criteria) this;
        }

        public Criteria andAPhoneEqualTo(String value) {
            addCriterion("a_phone =", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneNotEqualTo(String value) {
            addCriterion("a_phone <>", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneGreaterThan(String value) {
            addCriterion("a_phone >", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("a_phone >=", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneLessThan(String value) {
            addCriterion("a_phone <", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneLessThanOrEqualTo(String value) {
            addCriterion("a_phone <=", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneLike(String value) {
            addCriterion("a_phone like", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneNotLike(String value) {
            addCriterion("a_phone not like", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneIn(List<String> values) {
            addCriterion("a_phone in", values, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneNotIn(List<String> values) {
            addCriterion("a_phone not in", values, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneBetween(String value1, String value2) {
            addCriterion("a_phone between", value1, value2, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneNotBetween(String value1, String value2) {
            addCriterion("a_phone not between", value1, value2, "aPhone");
            return (Criteria) this;
        }

        public Criteria andARemarksIsNull() {
            addCriterion("a_remarks is null");
            return (Criteria) this;
        }

        public Criteria andARemarksIsNotNull() {
            addCriterion("a_remarks is not null");
            return (Criteria) this;
        }

        public Criteria andARemarksEqualTo(String value) {
            addCriterion("a_remarks =", value, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksNotEqualTo(String value) {
            addCriterion("a_remarks <>", value, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksGreaterThan(String value) {
            addCriterion("a_remarks >", value, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksGreaterThanOrEqualTo(String value) {
            addCriterion("a_remarks >=", value, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksLessThan(String value) {
            addCriterion("a_remarks <", value, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksLessThanOrEqualTo(String value) {
            addCriterion("a_remarks <=", value, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksLike(String value) {
            addCriterion("a_remarks like", value, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksNotLike(String value) {
            addCriterion("a_remarks not like", value, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksIn(List<String> values) {
            addCriterion("a_remarks in", values, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksNotIn(List<String> values) {
            addCriterion("a_remarks not in", values, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksBetween(String value1, String value2) {
            addCriterion("a_remarks between", value1, value2, "aRemarks");
            return (Criteria) this;
        }

        public Criteria andARemarksNotBetween(String value1, String value2) {
            addCriterion("a_remarks not between", value1, value2, "aRemarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_administrators
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}