package com.ojp.entity;

import java.util.ArrayList;
import java.util.List;

public class DisCityregionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public DisCityregionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCgIdIsNull() {
            addCriterion("cg_id is null");
            return (Criteria) this;
        }

        public Criteria andCgIdIsNotNull() {
            addCriterion("cg_id is not null");
            return (Criteria) this;
        }

        public Criteria andCgIdEqualTo(String value) {
            addCriterion("cg_id =", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdNotEqualTo(String value) {
            addCriterion("cg_id <>", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdGreaterThan(String value) {
            addCriterion("cg_id >", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdGreaterThanOrEqualTo(String value) {
            addCriterion("cg_id >=", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdLessThan(String value) {
            addCriterion("cg_id <", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdLessThanOrEqualTo(String value) {
            addCriterion("cg_id <=", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdLike(String value) {
            addCriterion("cg_id like", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdNotLike(String value) {
            addCriterion("cg_id not like", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdIn(List<String> values) {
            addCriterion("cg_id in", values, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdNotIn(List<String> values) {
            addCriterion("cg_id not in", values, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdBetween(String value1, String value2) {
            addCriterion("cg_id between", value1, value2, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdNotBetween(String value1, String value2) {
            addCriterion("cg_id not between", value1, value2, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgNameIsNull() {
            addCriterion("cg_name is null");
            return (Criteria) this;
        }

        public Criteria andCgNameIsNotNull() {
            addCriterion("cg_name is not null");
            return (Criteria) this;
        }

        public Criteria andCgNameEqualTo(String value) {
            addCriterion("cg_name =", value, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameNotEqualTo(String value) {
            addCriterion("cg_name <>", value, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameGreaterThan(String value) {
            addCriterion("cg_name >", value, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameGreaterThanOrEqualTo(String value) {
            addCriterion("cg_name >=", value, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameLessThan(String value) {
            addCriterion("cg_name <", value, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameLessThanOrEqualTo(String value) {
            addCriterion("cg_name <=", value, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameLike(String value) {
            addCriterion("cg_name like", value, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameNotLike(String value) {
            addCriterion("cg_name not like", value, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameIn(List<String> values) {
            addCriterion("cg_name in", values, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameNotIn(List<String> values) {
            addCriterion("cg_name not in", values, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameBetween(String value1, String value2) {
            addCriterion("cg_name between", value1, value2, "cgName");
            return (Criteria) this;
        }

        public Criteria andCgNameNotBetween(String value1, String value2) {
            addCriterion("cg_name not between", value1, value2, "cgName");
            return (Criteria) this;
        }

        public Criteria andDisCityIdIsNull() {
            addCriterion("dis_city_id is null");
            return (Criteria) this;
        }

        public Criteria andDisCityIdIsNotNull() {
            addCriterion("dis_city_id is not null");
            return (Criteria) this;
        }

        public Criteria andDisCityIdEqualTo(String value) {
            addCriterion("dis_city_id =", value, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdNotEqualTo(String value) {
            addCriterion("dis_city_id <>", value, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdGreaterThan(String value) {
            addCriterion("dis_city_id >", value, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdGreaterThanOrEqualTo(String value) {
            addCriterion("dis_city_id >=", value, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdLessThan(String value) {
            addCriterion("dis_city_id <", value, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdLessThanOrEqualTo(String value) {
            addCriterion("dis_city_id <=", value, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdLike(String value) {
            addCriterion("dis_city_id like", value, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdNotLike(String value) {
            addCriterion("dis_city_id not like", value, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdIn(List<String> values) {
            addCriterion("dis_city_id in", values, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdNotIn(List<String> values) {
            addCriterion("dis_city_id not in", values, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdBetween(String value1, String value2) {
            addCriterion("dis_city_id between", value1, value2, "disCityId");
            return (Criteria) this;
        }

        public Criteria andDisCityIdNotBetween(String value1, String value2) {
            addCriterion("dis_city_id not between", value1, value2, "disCityId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_cityregion
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}