package com.ojp.entity;

public class DisCityregion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_cityregion.cg_id
     *
     * @mbg.generated
     */
    private String cgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_cityregion.cg_name
     *
     * @mbg.generated
     */
    private String cgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_cityregion.dis_city_id
     *
     * @mbg.generated
     */
    private String disCityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_cityregion.cg_id
     *
     * @return the value of dis_cityregion.cg_id
     *
     * @mbg.generated
     */
    public String getCgId() {
        return cgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_cityregion.cg_id
     *
     * @param cgId the value for dis_cityregion.cg_id
     *
     * @mbg.generated
     */
    public void setCgId(String cgId) {
        this.cgId = cgId == null ? null : cgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_cityregion.cg_name
     *
     * @return the value of dis_cityregion.cg_name
     *
     * @mbg.generated
     */
    public String getCgName() {
        return cgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_cityregion.cg_name
     *
     * @param cgName the value for dis_cityregion.cg_name
     *
     * @mbg.generated
     */
    public void setCgName(String cgName) {
        this.cgName = cgName == null ? null : cgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_cityregion.dis_city_id
     *
     * @return the value of dis_cityregion.dis_city_id
     *
     * @mbg.generated
     */
    public String getDisCityId() {
        return disCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_cityregion.dis_city_id
     *
     * @param disCityId the value for dis_cityregion.dis_city_id
     *
     * @mbg.generated
     */
    public void setDisCityId(String disCityId) {
        this.disCityId = disCityId == null ? null : disCityId.trim();
    }
}