package com.ojp.entity;

public class DisCity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_city.dis_city_id
     *
     * @mbg.generated
     */
    private String disCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_city.dis_city_name
     *
     * @mbg.generated
     */
    private String disCityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_city.p_id
     *
     * @mbg.generated
     */
    private String pId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_city.dis_city_id
     *
     * @return the value of dis_city.dis_city_id
     *
     * @mbg.generated
     */
    public String getDisCityId() {
        return disCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_city.dis_city_id
     *
     * @param disCityId the value for dis_city.dis_city_id
     *
     * @mbg.generated
     */
    public void setDisCityId(String disCityId) {
        this.disCityId = disCityId == null ? null : disCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_city.dis_city_name
     *
     * @return the value of dis_city.dis_city_name
     *
     * @mbg.generated
     */
    public String getDisCityName() {
        return disCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_city.dis_city_name
     *
     * @param disCityName the value for dis_city.dis_city_name
     *
     * @mbg.generated
     */
    public void setDisCityName(String disCityName) {
        this.disCityName = disCityName == null ? null : disCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_city.p_id
     *
     * @return the value of dis_city.p_id
     *
     * @mbg.generated
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_city.p_id
     *
     * @param pId the value for dis_city.p_id
     *
     * @mbg.generated
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }
}