package com.ojp.entity;

import java.util.Date;

public class DisConsumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_consumer.c_id
     *
     * @mbg.generated
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_consumer.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_consumer.c_sex
     *
     * @mbg.generated
     */
    private Integer cSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_consumer.u_number
     *
     * @mbg.generated
     */
    private String uNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_consumer.c_pwd
     *
     * @mbg.generated
     */
    private String cPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_consumer.c_phone
     *
     * @mbg.generated
     */
    private String cPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_consumer.c_brithday
     *
     * @mbg.generated
     */
    private Date cBrithday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_consumer.c_address
     *
     * @mbg.generated
     */
    private String cAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_consumer.c_remarks
     *
     * @mbg.generated
     */
    private String cRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_consumer.c_id
     *
     * @return the value of dis_consumer.c_id
     *
     * @mbg.generated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_consumer.c_id
     *
     * @param cId the value for dis_consumer.c_id
     *
     * @mbg.generated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_consumer.c_name
     *
     * @return the value of dis_consumer.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_consumer.c_name
     *
     * @param cName the value for dis_consumer.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_consumer.c_sex
     *
     * @return the value of dis_consumer.c_sex
     *
     * @mbg.generated
     */
    public Integer getcSex() {
        return cSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_consumer.c_sex
     *
     * @param cSex the value for dis_consumer.c_sex
     *
     * @mbg.generated
     */
    public void setcSex(Integer cSex) {
        this.cSex = cSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_consumer.u_number
     *
     * @return the value of dis_consumer.u_number
     *
     * @mbg.generated
     */
    public String getuNumber() {
        return uNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_consumer.u_number
     *
     * @param uNumber the value for dis_consumer.u_number
     *
     * @mbg.generated
     */
    public void setuNumber(String uNumber) {
        this.uNumber = uNumber == null ? null : uNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_consumer.c_pwd
     *
     * @return the value of dis_consumer.c_pwd
     *
     * @mbg.generated
     */
    public String getcPwd() {
        return cPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_consumer.c_pwd
     *
     * @param cPwd the value for dis_consumer.c_pwd
     *
     * @mbg.generated
     */
    public void setcPwd(String cPwd) {
        this.cPwd = cPwd == null ? null : cPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_consumer.c_phone
     *
     * @return the value of dis_consumer.c_phone
     *
     * @mbg.generated
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_consumer.c_phone
     *
     * @param cPhone the value for dis_consumer.c_phone
     *
     * @mbg.generated
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_consumer.c_brithday
     *
     * @return the value of dis_consumer.c_brithday
     *
     * @mbg.generated
     */
    public Date getcBrithday() {
        return cBrithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_consumer.c_brithday
     *
     * @param cBrithday the value for dis_consumer.c_brithday
     *
     * @mbg.generated
     */
    public void setcBrithday(Date cBrithday) {
        this.cBrithday = cBrithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_consumer.c_address
     *
     * @return the value of dis_consumer.c_address
     *
     * @mbg.generated
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_consumer.c_address
     *
     * @param cAddress the value for dis_consumer.c_address
     *
     * @mbg.generated
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress == null ? null : cAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_consumer.c_remarks
     *
     * @return the value of dis_consumer.c_remarks
     *
     * @mbg.generated
     */
    public String getcRemarks() {
        return cRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_consumer.c_remarks
     *
     * @param cRemarks the value for dis_consumer.c_remarks
     *
     * @mbg.generated
     */
    public void setcRemarks(String cRemarks) {
        this.cRemarks = cRemarks == null ? null : cRemarks.trim();
    }
}