package com.ojp.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DisHandoversExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public DisHandoversExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHStartdisCityIsNull() {
            addCriterion("h_startdis_city is null");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityIsNotNull() {
            addCriterion("h_startdis_city is not null");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityEqualTo(String value) {
            addCriterion("h_startdis_city =", value, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityNotEqualTo(String value) {
            addCriterion("h_startdis_city <>", value, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityGreaterThan(String value) {
            addCriterion("h_startdis_city >", value, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityGreaterThanOrEqualTo(String value) {
            addCriterion("h_startdis_city >=", value, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityLessThan(String value) {
            addCriterion("h_startdis_city <", value, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityLessThanOrEqualTo(String value) {
            addCriterion("h_startdis_city <=", value, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityLike(String value) {
            addCriterion("h_startdis_city like", value, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityNotLike(String value) {
            addCriterion("h_startdis_city not like", value, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityIn(List<String> values) {
            addCriterion("h_startdis_city in", values, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityNotIn(List<String> values) {
            addCriterion("h_startdis_city not in", values, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityBetween(String value1, String value2) {
            addCriterion("h_startdis_city between", value1, value2, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHStartdisCityNotBetween(String value1, String value2) {
            addCriterion("h_startdis_city not between", value1, value2, "hStartdisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityIsNull() {
            addCriterion("h_enddis_city is null");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityIsNotNull() {
            addCriterion("h_enddis_city is not null");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityEqualTo(String value) {
            addCriterion("h_enddis_city =", value, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityNotEqualTo(String value) {
            addCriterion("h_enddis_city <>", value, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityGreaterThan(String value) {
            addCriterion("h_enddis_city >", value, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityGreaterThanOrEqualTo(String value) {
            addCriterion("h_enddis_city >=", value, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityLessThan(String value) {
            addCriterion("h_enddis_city <", value, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityLessThanOrEqualTo(String value) {
            addCriterion("h_enddis_city <=", value, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityLike(String value) {
            addCriterion("h_enddis_city like", value, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityNotLike(String value) {
            addCriterion("h_enddis_city not like", value, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityIn(List<String> values) {
            addCriterion("h_enddis_city in", values, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityNotIn(List<String> values) {
            addCriterion("h_enddis_city not in", values, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityBetween(String value1, String value2) {
            addCriterion("h_enddis_city between", value1, value2, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHEnddisCityNotBetween(String value1, String value2) {
            addCriterion("h_enddis_city not between", value1, value2, "hEnddisCity");
            return (Criteria) this;
        }

        public Criteria andHArriveIsNull() {
            addCriterion("h_arrive is null");
            return (Criteria) this;
        }

        public Criteria andHArriveIsNotNull() {
            addCriterion("h_arrive is not null");
            return (Criteria) this;
        }

        public Criteria andHArriveEqualTo(String value) {
            addCriterion("h_arrive =", value, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveNotEqualTo(String value) {
            addCriterion("h_arrive <>", value, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveGreaterThan(String value) {
            addCriterion("h_arrive >", value, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveGreaterThanOrEqualTo(String value) {
            addCriterion("h_arrive >=", value, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveLessThan(String value) {
            addCriterion("h_arrive <", value, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveLessThanOrEqualTo(String value) {
            addCriterion("h_arrive <=", value, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveLike(String value) {
            addCriterion("h_arrive like", value, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveNotLike(String value) {
            addCriterion("h_arrive not like", value, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveIn(List<String> values) {
            addCriterion("h_arrive in", values, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveNotIn(List<String> values) {
            addCriterion("h_arrive not in", values, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveBetween(String value1, String value2) {
            addCriterion("h_arrive between", value1, value2, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHArriveNotBetween(String value1, String value2) {
            addCriterion("h_arrive not between", value1, value2, "hArrive");
            return (Criteria) this;
        }

        public Criteria andHStateIsNull() {
            addCriterion("h_state is null");
            return (Criteria) this;
        }

        public Criteria andHStateIsNotNull() {
            addCriterion("h_state is not null");
            return (Criteria) this;
        }

        public Criteria andHStateEqualTo(Integer value) {
            addCriterion("h_state =", value, "hState");
            return (Criteria) this;
        }

        public Criteria andHStateNotEqualTo(Integer value) {
            addCriterion("h_state <>", value, "hState");
            return (Criteria) this;
        }

        public Criteria andHStateGreaterThan(Integer value) {
            addCriterion("h_state >", value, "hState");
            return (Criteria) this;
        }

        public Criteria andHStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_state >=", value, "hState");
            return (Criteria) this;
        }

        public Criteria andHStateLessThan(Integer value) {
            addCriterion("h_state <", value, "hState");
            return (Criteria) this;
        }

        public Criteria andHStateLessThanOrEqualTo(Integer value) {
            addCriterion("h_state <=", value, "hState");
            return (Criteria) this;
        }

        public Criteria andHStateIn(List<Integer> values) {
            addCriterion("h_state in", values, "hState");
            return (Criteria) this;
        }

        public Criteria andHStateNotIn(List<Integer> values) {
            addCriterion("h_state not in", values, "hState");
            return (Criteria) this;
        }

        public Criteria andHStateBetween(Integer value1, Integer value2) {
            addCriterion("h_state between", value1, value2, "hState");
            return (Criteria) this;
        }

        public Criteria andHStateNotBetween(Integer value1, Integer value2) {
            addCriterion("h_state not between", value1, value2, "hState");
            return (Criteria) this;
        }

        public Criteria andHGenerateIsNull() {
            addCriterion("h_generate is null");
            return (Criteria) this;
        }

        public Criteria andHGenerateIsNotNull() {
            addCriterion("h_generate is not null");
            return (Criteria) this;
        }

        public Criteria andHGenerateEqualTo(Date value) {
            addCriterion("h_generate =", value, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHGenerateNotEqualTo(Date value) {
            addCriterion("h_generate <>", value, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHGenerateGreaterThan(Date value) {
            addCriterion("h_generate >", value, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHGenerateGreaterThanOrEqualTo(Date value) {
            addCriterion("h_generate >=", value, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHGenerateLessThan(Date value) {
            addCriterion("h_generate <", value, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHGenerateLessThanOrEqualTo(Date value) {
            addCriterion("h_generate <=", value, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHGenerateIn(List<Date> values) {
            addCriterion("h_generate in", values, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHGenerateNotIn(List<Date> values) {
            addCriterion("h_generate not in", values, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHGenerateBetween(Date value1, Date value2) {
            addCriterion("h_generate between", value1, value2, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHGenerateNotBetween(Date value1, Date value2) {
            addCriterion("h_generate not between", value1, value2, "hGenerate");
            return (Criteria) this;
        }

        public Criteria andHRemarksIsNull() {
            addCriterion("h_remarks is null");
            return (Criteria) this;
        }

        public Criteria andHRemarksIsNotNull() {
            addCriterion("h_remarks is not null");
            return (Criteria) this;
        }

        public Criteria andHRemarksEqualTo(String value) {
            addCriterion("h_remarks =", value, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksNotEqualTo(String value) {
            addCriterion("h_remarks <>", value, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksGreaterThan(String value) {
            addCriterion("h_remarks >", value, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("h_remarks >=", value, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksLessThan(String value) {
            addCriterion("h_remarks <", value, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksLessThanOrEqualTo(String value) {
            addCriterion("h_remarks <=", value, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksLike(String value) {
            addCriterion("h_remarks like", value, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksNotLike(String value) {
            addCriterion("h_remarks not like", value, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksIn(List<String> values) {
            addCriterion("h_remarks in", values, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksNotIn(List<String> values) {
            addCriterion("h_remarks not in", values, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksBetween(String value1, String value2) {
            addCriterion("h_remarks between", value1, value2, "hRemarks");
            return (Criteria) this;
        }

        public Criteria andHRemarksNotBetween(String value1, String value2) {
            addCriterion("h_remarks not between", value1, value2, "hRemarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_handovers
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_handovers
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}