package com.ojp.entity;

public class DisOrders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_id
     *
     * @mbg.generated
     */
    private String oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_style
     *
     * @mbg.generated
     */
    private String oStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_handovernumber
     *
     * @mbg.generated
     */
    private String oHandovernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_goodsname
     *
     * @mbg.generated
     */
    private String oGoodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_goodsweight
     *
     * @mbg.generated
     */
    private Integer oGoodsweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_mailer
     *
     * @mbg.generated
     */
    private String oMailer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_maileraddress
     *
     * @mbg.generated
     */
    private String oMaileraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_collectaddress
     *
     * @mbg.generated
     */
    private String oCollectaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_dis_ordersstate
     *
     * @mbg.generated
     */
    private Integer oDisOrdersstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_mailerphone
     *
     * @mbg.generated
     */
    private String oMailerphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_collecter
     *
     * @mbg.generated
     */
    private String oCollecter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_collectphont
     *
     * @mbg.generated
     */
    private String oCollectphont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_startdis_city
     *
     * @mbg.generated
     */
    private String oStartdisCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_midpointdis_city
     *
     * @mbg.generated
     */
    private String oMidpointdisCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_enddis_city
     *
     * @mbg.generated
     */
    private String oEnddisCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_shippingprice
     *
     * @mbg.generated
     */
    private Long oShippingprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_Distribution
     *
     * @mbg.generated
     */
    private Long oDistribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_transport
     *
     * @mbg.generated
     */
    private Long oTransport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_price
     *
     * @mbg.generated
     */
    private String oPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_dis_vehicle
     *
     * @mbg.generated
     */
    private String oDisVehicle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_orders.o_remarks
     *
     * @mbg.generated
     */
    private String oRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_id
     *
     * @return the value of dis_orders.o_id
     *
     * @mbg.generated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_id
     *
     * @param oId the value for dis_orders.o_id
     *
     * @mbg.generated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_style
     *
     * @return the value of dis_orders.o_style
     *
     * @mbg.generated
     */
    public String getoStyle() {
        return oStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_style
     *
     * @param oStyle the value for dis_orders.o_style
     *
     * @mbg.generated
     */
    public void setoStyle(String oStyle) {
        this.oStyle = oStyle == null ? null : oStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_handovernumber
     *
     * @return the value of dis_orders.o_handovernumber
     *
     * @mbg.generated
     */
    public String getoHandovernumber() {
        return oHandovernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_handovernumber
     *
     * @param oHandovernumber the value for dis_orders.o_handovernumber
     *
     * @mbg.generated
     */
    public void setoHandovernumber(String oHandovernumber) {
        this.oHandovernumber = oHandovernumber == null ? null : oHandovernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_goodsname
     *
     * @return the value of dis_orders.o_goodsname
     *
     * @mbg.generated
     */
    public String getoGoodsname() {
        return oGoodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_goodsname
     *
     * @param oGoodsname the value for dis_orders.o_goodsname
     *
     * @mbg.generated
     */
    public void setoGoodsname(String oGoodsname) {
        this.oGoodsname = oGoodsname == null ? null : oGoodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_goodsweight
     *
     * @return the value of dis_orders.o_goodsweight
     *
     * @mbg.generated
     */
    public Integer getoGoodsweight() {
        return oGoodsweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_goodsweight
     *
     * @param oGoodsweight the value for dis_orders.o_goodsweight
     *
     * @mbg.generated
     */
    public void setoGoodsweight(Integer oGoodsweight) {
        this.oGoodsweight = oGoodsweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_mailer
     *
     * @return the value of dis_orders.o_mailer
     *
     * @mbg.generated
     */
    public String getoMailer() {
        return oMailer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_mailer
     *
     * @param oMailer the value for dis_orders.o_mailer
     *
     * @mbg.generated
     */
    public void setoMailer(String oMailer) {
        this.oMailer = oMailer == null ? null : oMailer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_maileraddress
     *
     * @return the value of dis_orders.o_maileraddress
     *
     * @mbg.generated
     */
    public String getoMaileraddress() {
        return oMaileraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_maileraddress
     *
     * @param oMaileraddress the value for dis_orders.o_maileraddress
     *
     * @mbg.generated
     */
    public void setoMaileraddress(String oMaileraddress) {
        this.oMaileraddress = oMaileraddress == null ? null : oMaileraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_collectaddress
     *
     * @return the value of dis_orders.o_collectaddress
     *
     * @mbg.generated
     */
    public String getoCollectaddress() {
        return oCollectaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_collectaddress
     *
     * @param oCollectaddress the value for dis_orders.o_collectaddress
     *
     * @mbg.generated
     */
    public void setoCollectaddress(String oCollectaddress) {
        this.oCollectaddress = oCollectaddress == null ? null : oCollectaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_dis_ordersstate
     *
     * @return the value of dis_orders.o_dis_ordersstate
     *
     * @mbg.generated
     */
    public Integer getoDisOrdersstate() {
        return oDisOrdersstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_dis_ordersstate
     *
     * @param oDisOrdersstate the value for dis_orders.o_dis_ordersstate
     *
     * @mbg.generated
     */
    public void setoDisOrdersstate(Integer oDisOrdersstate) {
        this.oDisOrdersstate = oDisOrdersstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_mailerphone
     *
     * @return the value of dis_orders.o_mailerphone
     *
     * @mbg.generated
     */
    public String getoMailerphone() {
        return oMailerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_mailerphone
     *
     * @param oMailerphone the value for dis_orders.o_mailerphone
     *
     * @mbg.generated
     */
    public void setoMailerphone(String oMailerphone) {
        this.oMailerphone = oMailerphone == null ? null : oMailerphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_collecter
     *
     * @return the value of dis_orders.o_collecter
     *
     * @mbg.generated
     */
    public String getoCollecter() {
        return oCollecter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_collecter
     *
     * @param oCollecter the value for dis_orders.o_collecter
     *
     * @mbg.generated
     */
    public void setoCollecter(String oCollecter) {
        this.oCollecter = oCollecter == null ? null : oCollecter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_collectphont
     *
     * @return the value of dis_orders.o_collectphont
     *
     * @mbg.generated
     */
    public String getoCollectphont() {
        return oCollectphont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_collectphont
     *
     * @param oCollectphont the value for dis_orders.o_collectphont
     *
     * @mbg.generated
     */
    public void setoCollectphont(String oCollectphont) {
        this.oCollectphont = oCollectphont == null ? null : oCollectphont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_startdis_city
     *
     * @return the value of dis_orders.o_startdis_city
     *
     * @mbg.generated
     */
    public String getoStartdisCity() {
        return oStartdisCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_startdis_city
     *
     * @param oStartdisCity the value for dis_orders.o_startdis_city
     *
     * @mbg.generated
     */
    public void setoStartdisCity(String oStartdisCity) {
        this.oStartdisCity = oStartdisCity == null ? null : oStartdisCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_midpointdis_city
     *
     * @return the value of dis_orders.o_midpointdis_city
     *
     * @mbg.generated
     */
    public String getoMidpointdisCity() {
        return oMidpointdisCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_midpointdis_city
     *
     * @param oMidpointdisCity the value for dis_orders.o_midpointdis_city
     *
     * @mbg.generated
     */
    public void setoMidpointdisCity(String oMidpointdisCity) {
        this.oMidpointdisCity = oMidpointdisCity == null ? null : oMidpointdisCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_enddis_city
     *
     * @return the value of dis_orders.o_enddis_city
     *
     * @mbg.generated
     */
    public String getoEnddisCity() {
        return oEnddisCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_enddis_city
     *
     * @param oEnddisCity the value for dis_orders.o_enddis_city
     *
     * @mbg.generated
     */
    public void setoEnddisCity(String oEnddisCity) {
        this.oEnddisCity = oEnddisCity == null ? null : oEnddisCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_shippingprice
     *
     * @return the value of dis_orders.o_shippingprice
     *
     * @mbg.generated
     */
    public Long getoShippingprice() {
        return oShippingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_shippingprice
     *
     * @param oShippingprice the value for dis_orders.o_shippingprice
     *
     * @mbg.generated
     */
    public void setoShippingprice(Long oShippingprice) {
        this.oShippingprice = oShippingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_Distribution
     *
     * @return the value of dis_orders.o_Distribution
     *
     * @mbg.generated
     */
    public Long getoDistribution() {
        return oDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_Distribution
     *
     * @param oDistribution the value for dis_orders.o_Distribution
     *
     * @mbg.generated
     */
    public void setoDistribution(Long oDistribution) {
        this.oDistribution = oDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_transport
     *
     * @return the value of dis_orders.o_transport
     *
     * @mbg.generated
     */
    public Long getoTransport() {
        return oTransport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_transport
     *
     * @param oTransport the value for dis_orders.o_transport
     *
     * @mbg.generated
     */
    public void setoTransport(Long oTransport) {
        this.oTransport = oTransport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_price
     *
     * @return the value of dis_orders.o_price
     *
     * @mbg.generated
     */
    public String getoPrice() {
        return oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_price
     *
     * @param oPrice the value for dis_orders.o_price
     *
     * @mbg.generated
     */
    public void setoPrice(String oPrice) {
        this.oPrice = oPrice == null ? null : oPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_dis_vehicle
     *
     * @return the value of dis_orders.o_dis_vehicle
     *
     * @mbg.generated
     */
    public String getoDisVehicle() {
        return oDisVehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_dis_vehicle
     *
     * @param oDisVehicle the value for dis_orders.o_dis_vehicle
     *
     * @mbg.generated
     */
    public void setoDisVehicle(String oDisVehicle) {
        this.oDisVehicle = oDisVehicle == null ? null : oDisVehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_orders.o_remarks
     *
     * @return the value of dis_orders.o_remarks
     *
     * @mbg.generated
     */
    public String getoRemarks() {
        return oRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_orders.o_remarks
     *
     * @param oRemarks the value for dis_orders.o_remarks
     *
     * @mbg.generated
     */
    public void setoRemarks(String oRemarks) {
        this.oRemarks = oRemarks == null ? null : oRemarks.trim();
    }
}