package com.ojp.entity;

import java.util.ArrayList;
import java.util.List;

public class DisOrdersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public DisOrdersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOIdIsNull() {
            addCriterion("o_id is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("o_id is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(String value) {
            addCriterion("o_id =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(String value) {
            addCriterion("o_id <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(String value) {
            addCriterion("o_id >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(String value) {
            addCriterion("o_id >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(String value) {
            addCriterion("o_id <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(String value) {
            addCriterion("o_id <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLike(String value) {
            addCriterion("o_id like", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotLike(String value) {
            addCriterion("o_id not like", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<String> values) {
            addCriterion("o_id in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<String> values) {
            addCriterion("o_id not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(String value1, String value2) {
            addCriterion("o_id between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(String value1, String value2) {
            addCriterion("o_id not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOStyleIsNull() {
            addCriterion("o_style is null");
            return (Criteria) this;
        }

        public Criteria andOStyleIsNotNull() {
            addCriterion("o_style is not null");
            return (Criteria) this;
        }

        public Criteria andOStyleEqualTo(String value) {
            addCriterion("o_style =", value, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleNotEqualTo(String value) {
            addCriterion("o_style <>", value, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleGreaterThan(String value) {
            addCriterion("o_style >", value, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleGreaterThanOrEqualTo(String value) {
            addCriterion("o_style >=", value, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleLessThan(String value) {
            addCriterion("o_style <", value, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleLessThanOrEqualTo(String value) {
            addCriterion("o_style <=", value, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleLike(String value) {
            addCriterion("o_style like", value, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleNotLike(String value) {
            addCriterion("o_style not like", value, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleIn(List<String> values) {
            addCriterion("o_style in", values, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleNotIn(List<String> values) {
            addCriterion("o_style not in", values, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleBetween(String value1, String value2) {
            addCriterion("o_style between", value1, value2, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOStyleNotBetween(String value1, String value2) {
            addCriterion("o_style not between", value1, value2, "oStyle");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberIsNull() {
            addCriterion("o_handovernumber is null");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberIsNotNull() {
            addCriterion("o_handovernumber is not null");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberEqualTo(String value) {
            addCriterion("o_handovernumber =", value, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberNotEqualTo(String value) {
            addCriterion("o_handovernumber <>", value, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberGreaterThan(String value) {
            addCriterion("o_handovernumber >", value, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberGreaterThanOrEqualTo(String value) {
            addCriterion("o_handovernumber >=", value, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberLessThan(String value) {
            addCriterion("o_handovernumber <", value, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberLessThanOrEqualTo(String value) {
            addCriterion("o_handovernumber <=", value, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberLike(String value) {
            addCriterion("o_handovernumber like", value, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberNotLike(String value) {
            addCriterion("o_handovernumber not like", value, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberIn(List<String> values) {
            addCriterion("o_handovernumber in", values, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberNotIn(List<String> values) {
            addCriterion("o_handovernumber not in", values, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberBetween(String value1, String value2) {
            addCriterion("o_handovernumber between", value1, value2, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOHandovernumberNotBetween(String value1, String value2) {
            addCriterion("o_handovernumber not between", value1, value2, "oHandovernumber");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameIsNull() {
            addCriterion("o_goodsname is null");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameIsNotNull() {
            addCriterion("o_goodsname is not null");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameEqualTo(String value) {
            addCriterion("o_goodsname =", value, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameNotEqualTo(String value) {
            addCriterion("o_goodsname <>", value, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameGreaterThan(String value) {
            addCriterion("o_goodsname >", value, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameGreaterThanOrEqualTo(String value) {
            addCriterion("o_goodsname >=", value, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameLessThan(String value) {
            addCriterion("o_goodsname <", value, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameLessThanOrEqualTo(String value) {
            addCriterion("o_goodsname <=", value, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameLike(String value) {
            addCriterion("o_goodsname like", value, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameNotLike(String value) {
            addCriterion("o_goodsname not like", value, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameIn(List<String> values) {
            addCriterion("o_goodsname in", values, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameNotIn(List<String> values) {
            addCriterion("o_goodsname not in", values, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameBetween(String value1, String value2) {
            addCriterion("o_goodsname between", value1, value2, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsnameNotBetween(String value1, String value2) {
            addCriterion("o_goodsname not between", value1, value2, "oGoodsname");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightIsNull() {
            addCriterion("o_goodsweight is null");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightIsNotNull() {
            addCriterion("o_goodsweight is not null");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightEqualTo(Integer value) {
            addCriterion("o_goodsweight =", value, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightNotEqualTo(Integer value) {
            addCriterion("o_goodsweight <>", value, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightGreaterThan(Integer value) {
            addCriterion("o_goodsweight >", value, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_goodsweight >=", value, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightLessThan(Integer value) {
            addCriterion("o_goodsweight <", value, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightLessThanOrEqualTo(Integer value) {
            addCriterion("o_goodsweight <=", value, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightIn(List<Integer> values) {
            addCriterion("o_goodsweight in", values, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightNotIn(List<Integer> values) {
            addCriterion("o_goodsweight not in", values, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightBetween(Integer value1, Integer value2) {
            addCriterion("o_goodsweight between", value1, value2, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOGoodsweightNotBetween(Integer value1, Integer value2) {
            addCriterion("o_goodsweight not between", value1, value2, "oGoodsweight");
            return (Criteria) this;
        }

        public Criteria andOMailerIsNull() {
            addCriterion("o_mailer is null");
            return (Criteria) this;
        }

        public Criteria andOMailerIsNotNull() {
            addCriterion("o_mailer is not null");
            return (Criteria) this;
        }

        public Criteria andOMailerEqualTo(String value) {
            addCriterion("o_mailer =", value, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerNotEqualTo(String value) {
            addCriterion("o_mailer <>", value, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerGreaterThan(String value) {
            addCriterion("o_mailer >", value, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerGreaterThanOrEqualTo(String value) {
            addCriterion("o_mailer >=", value, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerLessThan(String value) {
            addCriterion("o_mailer <", value, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerLessThanOrEqualTo(String value) {
            addCriterion("o_mailer <=", value, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerLike(String value) {
            addCriterion("o_mailer like", value, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerNotLike(String value) {
            addCriterion("o_mailer not like", value, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerIn(List<String> values) {
            addCriterion("o_mailer in", values, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerNotIn(List<String> values) {
            addCriterion("o_mailer not in", values, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerBetween(String value1, String value2) {
            addCriterion("o_mailer between", value1, value2, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMailerNotBetween(String value1, String value2) {
            addCriterion("o_mailer not between", value1, value2, "oMailer");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressIsNull() {
            addCriterion("o_maileraddress is null");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressIsNotNull() {
            addCriterion("o_maileraddress is not null");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressEqualTo(String value) {
            addCriterion("o_maileraddress =", value, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressNotEqualTo(String value) {
            addCriterion("o_maileraddress <>", value, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressGreaterThan(String value) {
            addCriterion("o_maileraddress >", value, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressGreaterThanOrEqualTo(String value) {
            addCriterion("o_maileraddress >=", value, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressLessThan(String value) {
            addCriterion("o_maileraddress <", value, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressLessThanOrEqualTo(String value) {
            addCriterion("o_maileraddress <=", value, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressLike(String value) {
            addCriterion("o_maileraddress like", value, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressNotLike(String value) {
            addCriterion("o_maileraddress not like", value, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressIn(List<String> values) {
            addCriterion("o_maileraddress in", values, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressNotIn(List<String> values) {
            addCriterion("o_maileraddress not in", values, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressBetween(String value1, String value2) {
            addCriterion("o_maileraddress between", value1, value2, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOMaileraddressNotBetween(String value1, String value2) {
            addCriterion("o_maileraddress not between", value1, value2, "oMaileraddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressIsNull() {
            addCriterion("o_collectaddress is null");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressIsNotNull() {
            addCriterion("o_collectaddress is not null");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressEqualTo(String value) {
            addCriterion("o_collectaddress =", value, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressNotEqualTo(String value) {
            addCriterion("o_collectaddress <>", value, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressGreaterThan(String value) {
            addCriterion("o_collectaddress >", value, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressGreaterThanOrEqualTo(String value) {
            addCriterion("o_collectaddress >=", value, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressLessThan(String value) {
            addCriterion("o_collectaddress <", value, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressLessThanOrEqualTo(String value) {
            addCriterion("o_collectaddress <=", value, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressLike(String value) {
            addCriterion("o_collectaddress like", value, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressNotLike(String value) {
            addCriterion("o_collectaddress not like", value, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressIn(List<String> values) {
            addCriterion("o_collectaddress in", values, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressNotIn(List<String> values) {
            addCriterion("o_collectaddress not in", values, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressBetween(String value1, String value2) {
            addCriterion("o_collectaddress between", value1, value2, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andOCollectaddressNotBetween(String value1, String value2) {
            addCriterion("o_collectaddress not between", value1, value2, "oCollectaddress");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateIsNull() {
            addCriterion("o_dis_ordersstate is null");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateIsNotNull() {
            addCriterion("o_dis_ordersstate is not null");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateEqualTo(Integer value) {
            addCriterion("o_dis_ordersstate =", value, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateNotEqualTo(Integer value) {
            addCriterion("o_dis_ordersstate <>", value, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateGreaterThan(Integer value) {
            addCriterion("o_dis_ordersstate >", value, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_dis_ordersstate >=", value, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateLessThan(Integer value) {
            addCriterion("o_dis_ordersstate <", value, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateLessThanOrEqualTo(Integer value) {
            addCriterion("o_dis_ordersstate <=", value, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateIn(List<Integer> values) {
            addCriterion("o_dis_ordersstate in", values, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateNotIn(List<Integer> values) {
            addCriterion("o_dis_ordersstate not in", values, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateBetween(Integer value1, Integer value2) {
            addCriterion("o_dis_ordersstate between", value1, value2, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andODisOrdersstateNotBetween(Integer value1, Integer value2) {
            addCriterion("o_dis_ordersstate not between", value1, value2, "oDisOrdersstate");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneIsNull() {
            addCriterion("o_mailerphone is null");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneIsNotNull() {
            addCriterion("o_mailerphone is not null");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneEqualTo(String value) {
            addCriterion("o_mailerphone =", value, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneNotEqualTo(String value) {
            addCriterion("o_mailerphone <>", value, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneGreaterThan(String value) {
            addCriterion("o_mailerphone >", value, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneGreaterThanOrEqualTo(String value) {
            addCriterion("o_mailerphone >=", value, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneLessThan(String value) {
            addCriterion("o_mailerphone <", value, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneLessThanOrEqualTo(String value) {
            addCriterion("o_mailerphone <=", value, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneLike(String value) {
            addCriterion("o_mailerphone like", value, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneNotLike(String value) {
            addCriterion("o_mailerphone not like", value, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneIn(List<String> values) {
            addCriterion("o_mailerphone in", values, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneNotIn(List<String> values) {
            addCriterion("o_mailerphone not in", values, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneBetween(String value1, String value2) {
            addCriterion("o_mailerphone between", value1, value2, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOMailerphoneNotBetween(String value1, String value2) {
            addCriterion("o_mailerphone not between", value1, value2, "oMailerphone");
            return (Criteria) this;
        }

        public Criteria andOCollecterIsNull() {
            addCriterion("o_collecter is null");
            return (Criteria) this;
        }

        public Criteria andOCollecterIsNotNull() {
            addCriterion("o_collecter is not null");
            return (Criteria) this;
        }

        public Criteria andOCollecterEqualTo(String value) {
            addCriterion("o_collecter =", value, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterNotEqualTo(String value) {
            addCriterion("o_collecter <>", value, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterGreaterThan(String value) {
            addCriterion("o_collecter >", value, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterGreaterThanOrEqualTo(String value) {
            addCriterion("o_collecter >=", value, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterLessThan(String value) {
            addCriterion("o_collecter <", value, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterLessThanOrEqualTo(String value) {
            addCriterion("o_collecter <=", value, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterLike(String value) {
            addCriterion("o_collecter like", value, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterNotLike(String value) {
            addCriterion("o_collecter not like", value, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterIn(List<String> values) {
            addCriterion("o_collecter in", values, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterNotIn(List<String> values) {
            addCriterion("o_collecter not in", values, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterBetween(String value1, String value2) {
            addCriterion("o_collecter between", value1, value2, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollecterNotBetween(String value1, String value2) {
            addCriterion("o_collecter not between", value1, value2, "oCollecter");
            return (Criteria) this;
        }

        public Criteria andOCollectphontIsNull() {
            addCriterion("o_collectphont is null");
            return (Criteria) this;
        }

        public Criteria andOCollectphontIsNotNull() {
            addCriterion("o_collectphont is not null");
            return (Criteria) this;
        }

        public Criteria andOCollectphontEqualTo(String value) {
            addCriterion("o_collectphont =", value, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontNotEqualTo(String value) {
            addCriterion("o_collectphont <>", value, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontGreaterThan(String value) {
            addCriterion("o_collectphont >", value, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontGreaterThanOrEqualTo(String value) {
            addCriterion("o_collectphont >=", value, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontLessThan(String value) {
            addCriterion("o_collectphont <", value, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontLessThanOrEqualTo(String value) {
            addCriterion("o_collectphont <=", value, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontLike(String value) {
            addCriterion("o_collectphont like", value, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontNotLike(String value) {
            addCriterion("o_collectphont not like", value, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontIn(List<String> values) {
            addCriterion("o_collectphont in", values, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontNotIn(List<String> values) {
            addCriterion("o_collectphont not in", values, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontBetween(String value1, String value2) {
            addCriterion("o_collectphont between", value1, value2, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOCollectphontNotBetween(String value1, String value2) {
            addCriterion("o_collectphont not between", value1, value2, "oCollectphont");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityIsNull() {
            addCriterion("o_startdis_city is null");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityIsNotNull() {
            addCriterion("o_startdis_city is not null");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityEqualTo(String value) {
            addCriterion("o_startdis_city =", value, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityNotEqualTo(String value) {
            addCriterion("o_startdis_city <>", value, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityGreaterThan(String value) {
            addCriterion("o_startdis_city >", value, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityGreaterThanOrEqualTo(String value) {
            addCriterion("o_startdis_city >=", value, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityLessThan(String value) {
            addCriterion("o_startdis_city <", value, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityLessThanOrEqualTo(String value) {
            addCriterion("o_startdis_city <=", value, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityLike(String value) {
            addCriterion("o_startdis_city like", value, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityNotLike(String value) {
            addCriterion("o_startdis_city not like", value, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityIn(List<String> values) {
            addCriterion("o_startdis_city in", values, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityNotIn(List<String> values) {
            addCriterion("o_startdis_city not in", values, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityBetween(String value1, String value2) {
            addCriterion("o_startdis_city between", value1, value2, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOStartdisCityNotBetween(String value1, String value2) {
            addCriterion("o_startdis_city not between", value1, value2, "oStartdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityIsNull() {
            addCriterion("o_midpointdis_city is null");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityIsNotNull() {
            addCriterion("o_midpointdis_city is not null");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityEqualTo(String value) {
            addCriterion("o_midpointdis_city =", value, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityNotEqualTo(String value) {
            addCriterion("o_midpointdis_city <>", value, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityGreaterThan(String value) {
            addCriterion("o_midpointdis_city >", value, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityGreaterThanOrEqualTo(String value) {
            addCriterion("o_midpointdis_city >=", value, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityLessThan(String value) {
            addCriterion("o_midpointdis_city <", value, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityLessThanOrEqualTo(String value) {
            addCriterion("o_midpointdis_city <=", value, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityLike(String value) {
            addCriterion("o_midpointdis_city like", value, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityNotLike(String value) {
            addCriterion("o_midpointdis_city not like", value, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityIn(List<String> values) {
            addCriterion("o_midpointdis_city in", values, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityNotIn(List<String> values) {
            addCriterion("o_midpointdis_city not in", values, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityBetween(String value1, String value2) {
            addCriterion("o_midpointdis_city between", value1, value2, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOMidpointdisCityNotBetween(String value1, String value2) {
            addCriterion("o_midpointdis_city not between", value1, value2, "oMidpointdisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityIsNull() {
            addCriterion("o_enddis_city is null");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityIsNotNull() {
            addCriterion("o_enddis_city is not null");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityEqualTo(String value) {
            addCriterion("o_enddis_city =", value, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityNotEqualTo(String value) {
            addCriterion("o_enddis_city <>", value, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityGreaterThan(String value) {
            addCriterion("o_enddis_city >", value, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityGreaterThanOrEqualTo(String value) {
            addCriterion("o_enddis_city >=", value, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityLessThan(String value) {
            addCriterion("o_enddis_city <", value, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityLessThanOrEqualTo(String value) {
            addCriterion("o_enddis_city <=", value, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityLike(String value) {
            addCriterion("o_enddis_city like", value, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityNotLike(String value) {
            addCriterion("o_enddis_city not like", value, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityIn(List<String> values) {
            addCriterion("o_enddis_city in", values, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityNotIn(List<String> values) {
            addCriterion("o_enddis_city not in", values, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityBetween(String value1, String value2) {
            addCriterion("o_enddis_city between", value1, value2, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOEnddisCityNotBetween(String value1, String value2) {
            addCriterion("o_enddis_city not between", value1, value2, "oEnddisCity");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceIsNull() {
            addCriterion("o_shippingprice is null");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceIsNotNull() {
            addCriterion("o_shippingprice is not null");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceEqualTo(Long value) {
            addCriterion("o_shippingprice =", value, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceNotEqualTo(Long value) {
            addCriterion("o_shippingprice <>", value, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceGreaterThan(Long value) {
            addCriterion("o_shippingprice >", value, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceGreaterThanOrEqualTo(Long value) {
            addCriterion("o_shippingprice >=", value, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceLessThan(Long value) {
            addCriterion("o_shippingprice <", value, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceLessThanOrEqualTo(Long value) {
            addCriterion("o_shippingprice <=", value, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceIn(List<Long> values) {
            addCriterion("o_shippingprice in", values, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceNotIn(List<Long> values) {
            addCriterion("o_shippingprice not in", values, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceBetween(Long value1, Long value2) {
            addCriterion("o_shippingprice between", value1, value2, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andOShippingpriceNotBetween(Long value1, Long value2) {
            addCriterion("o_shippingprice not between", value1, value2, "oShippingprice");
            return (Criteria) this;
        }

        public Criteria andODistributionIsNull() {
            addCriterion("o_Distribution is null");
            return (Criteria) this;
        }

        public Criteria andODistributionIsNotNull() {
            addCriterion("o_Distribution is not null");
            return (Criteria) this;
        }

        public Criteria andODistributionEqualTo(Long value) {
            addCriterion("o_Distribution =", value, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andODistributionNotEqualTo(Long value) {
            addCriterion("o_Distribution <>", value, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andODistributionGreaterThan(Long value) {
            addCriterion("o_Distribution >", value, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andODistributionGreaterThanOrEqualTo(Long value) {
            addCriterion("o_Distribution >=", value, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andODistributionLessThan(Long value) {
            addCriterion("o_Distribution <", value, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andODistributionLessThanOrEqualTo(Long value) {
            addCriterion("o_Distribution <=", value, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andODistributionIn(List<Long> values) {
            addCriterion("o_Distribution in", values, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andODistributionNotIn(List<Long> values) {
            addCriterion("o_Distribution not in", values, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andODistributionBetween(Long value1, Long value2) {
            addCriterion("o_Distribution between", value1, value2, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andODistributionNotBetween(Long value1, Long value2) {
            addCriterion("o_Distribution not between", value1, value2, "oDistribution");
            return (Criteria) this;
        }

        public Criteria andOTransportIsNull() {
            addCriterion("o_transport is null");
            return (Criteria) this;
        }

        public Criteria andOTransportIsNotNull() {
            addCriterion("o_transport is not null");
            return (Criteria) this;
        }

        public Criteria andOTransportEqualTo(Long value) {
            addCriterion("o_transport =", value, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOTransportNotEqualTo(Long value) {
            addCriterion("o_transport <>", value, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOTransportGreaterThan(Long value) {
            addCriterion("o_transport >", value, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOTransportGreaterThanOrEqualTo(Long value) {
            addCriterion("o_transport >=", value, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOTransportLessThan(Long value) {
            addCriterion("o_transport <", value, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOTransportLessThanOrEqualTo(Long value) {
            addCriterion("o_transport <=", value, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOTransportIn(List<Long> values) {
            addCriterion("o_transport in", values, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOTransportNotIn(List<Long> values) {
            addCriterion("o_transport not in", values, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOTransportBetween(Long value1, Long value2) {
            addCriterion("o_transport between", value1, value2, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOTransportNotBetween(Long value1, Long value2) {
            addCriterion("o_transport not between", value1, value2, "oTransport");
            return (Criteria) this;
        }

        public Criteria andOPriceIsNull() {
            addCriterion("o_price is null");
            return (Criteria) this;
        }

        public Criteria andOPriceIsNotNull() {
            addCriterion("o_price is not null");
            return (Criteria) this;
        }

        public Criteria andOPriceEqualTo(String value) {
            addCriterion("o_price =", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotEqualTo(String value) {
            addCriterion("o_price <>", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceGreaterThan(String value) {
            addCriterion("o_price >", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceGreaterThanOrEqualTo(String value) {
            addCriterion("o_price >=", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceLessThan(String value) {
            addCriterion("o_price <", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceLessThanOrEqualTo(String value) {
            addCriterion("o_price <=", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceLike(String value) {
            addCriterion("o_price like", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotLike(String value) {
            addCriterion("o_price not like", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceIn(List<String> values) {
            addCriterion("o_price in", values, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotIn(List<String> values) {
            addCriterion("o_price not in", values, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceBetween(String value1, String value2) {
            addCriterion("o_price between", value1, value2, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotBetween(String value1, String value2) {
            addCriterion("o_price not between", value1, value2, "oPrice");
            return (Criteria) this;
        }

        public Criteria andODisVehicleIsNull() {
            addCriterion("o_dis_vehicle is null");
            return (Criteria) this;
        }

        public Criteria andODisVehicleIsNotNull() {
            addCriterion("o_dis_vehicle is not null");
            return (Criteria) this;
        }

        public Criteria andODisVehicleEqualTo(String value) {
            addCriterion("o_dis_vehicle =", value, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleNotEqualTo(String value) {
            addCriterion("o_dis_vehicle <>", value, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleGreaterThan(String value) {
            addCriterion("o_dis_vehicle >", value, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleGreaterThanOrEqualTo(String value) {
            addCriterion("o_dis_vehicle >=", value, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleLessThan(String value) {
            addCriterion("o_dis_vehicle <", value, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleLessThanOrEqualTo(String value) {
            addCriterion("o_dis_vehicle <=", value, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleLike(String value) {
            addCriterion("o_dis_vehicle like", value, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleNotLike(String value) {
            addCriterion("o_dis_vehicle not like", value, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleIn(List<String> values) {
            addCriterion("o_dis_vehicle in", values, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleNotIn(List<String> values) {
            addCriterion("o_dis_vehicle not in", values, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleBetween(String value1, String value2) {
            addCriterion("o_dis_vehicle between", value1, value2, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andODisVehicleNotBetween(String value1, String value2) {
            addCriterion("o_dis_vehicle not between", value1, value2, "oDisVehicle");
            return (Criteria) this;
        }

        public Criteria andORemarksIsNull() {
            addCriterion("o_remarks is null");
            return (Criteria) this;
        }

        public Criteria andORemarksIsNotNull() {
            addCriterion("o_remarks is not null");
            return (Criteria) this;
        }

        public Criteria andORemarksEqualTo(String value) {
            addCriterion("o_remarks =", value, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksNotEqualTo(String value) {
            addCriterion("o_remarks <>", value, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksGreaterThan(String value) {
            addCriterion("o_remarks >", value, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksGreaterThanOrEqualTo(String value) {
            addCriterion("o_remarks >=", value, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksLessThan(String value) {
            addCriterion("o_remarks <", value, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksLessThanOrEqualTo(String value) {
            addCriterion("o_remarks <=", value, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksLike(String value) {
            addCriterion("o_remarks like", value, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksNotLike(String value) {
            addCriterion("o_remarks not like", value, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksIn(List<String> values) {
            addCriterion("o_remarks in", values, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksNotIn(List<String> values) {
            addCriterion("o_remarks not in", values, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksBetween(String value1, String value2) {
            addCriterion("o_remarks between", value1, value2, "oRemarks");
            return (Criteria) this;
        }

        public Criteria andORemarksNotBetween(String value1, String value2) {
            addCriterion("o_remarks not between", value1, value2, "oRemarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_orders
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}