package com.ojp.entity;

public class DisRoute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.r_id
     *
     * @mbg.generated
     */
    private String rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.r_name
     *
     * @mbg.generated
     */
    private String rName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.p_startid
     *
     * @mbg.generated
     */
    private String pStartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.dis_city_startid
     *
     * @mbg.generated
     */
    private String disCityStartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.p_midpointid
     *
     * @mbg.generated
     */
    private String pMidpointid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.dis_city_midpointid
     *
     * @mbg.generated
     */
    private String disCityMidpointid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.p_endid
     *
     * @mbg.generated
     */
    private String pEndid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.dis_city_endid
     *
     * @mbg.generated
     */
    private String disCityEndid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.r_price
     *
     * @mbg.generated
     */
    private Long rPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_route.r_remarks
     *
     * @mbg.generated
     */
    private String rRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.r_id
     *
     * @return the value of dis_route.r_id
     *
     * @mbg.generated
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.r_id
     *
     * @param rId the value for dis_route.r_id
     *
     * @mbg.generated
     */
    public void setrId(String rId) {
        this.rId = rId == null ? null : rId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.r_name
     *
     * @return the value of dis_route.r_name
     *
     * @mbg.generated
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.r_name
     *
     * @param rName the value for dis_route.r_name
     *
     * @mbg.generated
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.p_startid
     *
     * @return the value of dis_route.p_startid
     *
     * @mbg.generated
     */
    public String getpStartid() {
        return pStartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.p_startid
     *
     * @param pStartid the value for dis_route.p_startid
     *
     * @mbg.generated
     */
    public void setpStartid(String pStartid) {
        this.pStartid = pStartid == null ? null : pStartid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.dis_city_startid
     *
     * @return the value of dis_route.dis_city_startid
     *
     * @mbg.generated
     */
    public String getDisCityStartid() {
        return disCityStartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.dis_city_startid
     *
     * @param disCityStartid the value for dis_route.dis_city_startid
     *
     * @mbg.generated
     */
    public void setDisCityStartid(String disCityStartid) {
        this.disCityStartid = disCityStartid == null ? null : disCityStartid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.p_midpointid
     *
     * @return the value of dis_route.p_midpointid
     *
     * @mbg.generated
     */
    public String getpMidpointid() {
        return pMidpointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.p_midpointid
     *
     * @param pMidpointid the value for dis_route.p_midpointid
     *
     * @mbg.generated
     */
    public void setpMidpointid(String pMidpointid) {
        this.pMidpointid = pMidpointid == null ? null : pMidpointid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.dis_city_midpointid
     *
     * @return the value of dis_route.dis_city_midpointid
     *
     * @mbg.generated
     */
    public String getDisCityMidpointid() {
        return disCityMidpointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.dis_city_midpointid
     *
     * @param disCityMidpointid the value for dis_route.dis_city_midpointid
     *
     * @mbg.generated
     */
    public void setDisCityMidpointid(String disCityMidpointid) {
        this.disCityMidpointid = disCityMidpointid == null ? null : disCityMidpointid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.p_endid
     *
     * @return the value of dis_route.p_endid
     *
     * @mbg.generated
     */
    public String getpEndid() {
        return pEndid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.p_endid
     *
     * @param pEndid the value for dis_route.p_endid
     *
     * @mbg.generated
     */
    public void setpEndid(String pEndid) {
        this.pEndid = pEndid == null ? null : pEndid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.dis_city_endid
     *
     * @return the value of dis_route.dis_city_endid
     *
     * @mbg.generated
     */
    public String getDisCityEndid() {
        return disCityEndid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.dis_city_endid
     *
     * @param disCityEndid the value for dis_route.dis_city_endid
     *
     * @mbg.generated
     */
    public void setDisCityEndid(String disCityEndid) {
        this.disCityEndid = disCityEndid == null ? null : disCityEndid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.r_price
     *
     * @return the value of dis_route.r_price
     *
     * @mbg.generated
     */
    public Long getrPrice() {
        return rPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.r_price
     *
     * @param rPrice the value for dis_route.r_price
     *
     * @mbg.generated
     */
    public void setrPrice(Long rPrice) {
        this.rPrice = rPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_route.r_remarks
     *
     * @return the value of dis_route.r_remarks
     *
     * @mbg.generated
     */
    public String getrRemarks() {
        return rRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_route.r_remarks
     *
     * @param rRemarks the value for dis_route.r_remarks
     *
     * @mbg.generated
     */
    public void setrRemarks(String rRemarks) {
        this.rRemarks = rRemarks == null ? null : rRemarks.trim();
    }
}