package com.ojp.entity;

import java.util.ArrayList;
import java.util.List;

public class DisRouteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public DisRouteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRIdIsNull() {
            addCriterion("r_id is null");
            return (Criteria) this;
        }

        public Criteria andRIdIsNotNull() {
            addCriterion("r_id is not null");
            return (Criteria) this;
        }

        public Criteria andRIdEqualTo(String value) {
            addCriterion("r_id =", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotEqualTo(String value) {
            addCriterion("r_id <>", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdGreaterThan(String value) {
            addCriterion("r_id >", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdGreaterThanOrEqualTo(String value) {
            addCriterion("r_id >=", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLessThan(String value) {
            addCriterion("r_id <", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLessThanOrEqualTo(String value) {
            addCriterion("r_id <=", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLike(String value) {
            addCriterion("r_id like", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotLike(String value) {
            addCriterion("r_id not like", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdIn(List<String> values) {
            addCriterion("r_id in", values, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotIn(List<String> values) {
            addCriterion("r_id not in", values, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdBetween(String value1, String value2) {
            addCriterion("r_id between", value1, value2, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotBetween(String value1, String value2) {
            addCriterion("r_id not between", value1, value2, "rId");
            return (Criteria) this;
        }

        public Criteria andRNameIsNull() {
            addCriterion("r_name is null");
            return (Criteria) this;
        }

        public Criteria andRNameIsNotNull() {
            addCriterion("r_name is not null");
            return (Criteria) this;
        }

        public Criteria andRNameEqualTo(String value) {
            addCriterion("r_name =", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotEqualTo(String value) {
            addCriterion("r_name <>", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThan(String value) {
            addCriterion("r_name >", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThanOrEqualTo(String value) {
            addCriterion("r_name >=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThan(String value) {
            addCriterion("r_name <", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThanOrEqualTo(String value) {
            addCriterion("r_name <=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLike(String value) {
            addCriterion("r_name like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotLike(String value) {
            addCriterion("r_name not like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameIn(List<String> values) {
            addCriterion("r_name in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotIn(List<String> values) {
            addCriterion("r_name not in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameBetween(String value1, String value2) {
            addCriterion("r_name between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotBetween(String value1, String value2) {
            addCriterion("r_name not between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andPStartidIsNull() {
            addCriterion("p_startid is null");
            return (Criteria) this;
        }

        public Criteria andPStartidIsNotNull() {
            addCriterion("p_startid is not null");
            return (Criteria) this;
        }

        public Criteria andPStartidEqualTo(String value) {
            addCriterion("p_startid =", value, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidNotEqualTo(String value) {
            addCriterion("p_startid <>", value, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidGreaterThan(String value) {
            addCriterion("p_startid >", value, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidGreaterThanOrEqualTo(String value) {
            addCriterion("p_startid >=", value, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidLessThan(String value) {
            addCriterion("p_startid <", value, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidLessThanOrEqualTo(String value) {
            addCriterion("p_startid <=", value, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidLike(String value) {
            addCriterion("p_startid like", value, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidNotLike(String value) {
            addCriterion("p_startid not like", value, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidIn(List<String> values) {
            addCriterion("p_startid in", values, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidNotIn(List<String> values) {
            addCriterion("p_startid not in", values, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidBetween(String value1, String value2) {
            addCriterion("p_startid between", value1, value2, "pStartid");
            return (Criteria) this;
        }

        public Criteria andPStartidNotBetween(String value1, String value2) {
            addCriterion("p_startid not between", value1, value2, "pStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidIsNull() {
            addCriterion("dis_city_startid is null");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidIsNotNull() {
            addCriterion("dis_city_startid is not null");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidEqualTo(String value) {
            addCriterion("dis_city_startid =", value, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidNotEqualTo(String value) {
            addCriterion("dis_city_startid <>", value, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidGreaterThan(String value) {
            addCriterion("dis_city_startid >", value, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidGreaterThanOrEqualTo(String value) {
            addCriterion("dis_city_startid >=", value, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidLessThan(String value) {
            addCriterion("dis_city_startid <", value, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidLessThanOrEqualTo(String value) {
            addCriterion("dis_city_startid <=", value, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidLike(String value) {
            addCriterion("dis_city_startid like", value, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidNotLike(String value) {
            addCriterion("dis_city_startid not like", value, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidIn(List<String> values) {
            addCriterion("dis_city_startid in", values, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidNotIn(List<String> values) {
            addCriterion("dis_city_startid not in", values, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidBetween(String value1, String value2) {
            addCriterion("dis_city_startid between", value1, value2, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andDisCityStartidNotBetween(String value1, String value2) {
            addCriterion("dis_city_startid not between", value1, value2, "disCityStartid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidIsNull() {
            addCriterion("p_midpointid is null");
            return (Criteria) this;
        }

        public Criteria andPMidpointidIsNotNull() {
            addCriterion("p_midpointid is not null");
            return (Criteria) this;
        }

        public Criteria andPMidpointidEqualTo(String value) {
            addCriterion("p_midpointid =", value, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidNotEqualTo(String value) {
            addCriterion("p_midpointid <>", value, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidGreaterThan(String value) {
            addCriterion("p_midpointid >", value, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidGreaterThanOrEqualTo(String value) {
            addCriterion("p_midpointid >=", value, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidLessThan(String value) {
            addCriterion("p_midpointid <", value, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidLessThanOrEqualTo(String value) {
            addCriterion("p_midpointid <=", value, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidLike(String value) {
            addCriterion("p_midpointid like", value, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidNotLike(String value) {
            addCriterion("p_midpointid not like", value, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidIn(List<String> values) {
            addCriterion("p_midpointid in", values, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidNotIn(List<String> values) {
            addCriterion("p_midpointid not in", values, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidBetween(String value1, String value2) {
            addCriterion("p_midpointid between", value1, value2, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andPMidpointidNotBetween(String value1, String value2) {
            addCriterion("p_midpointid not between", value1, value2, "pMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidIsNull() {
            addCriterion("dis_city_midpointid is null");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidIsNotNull() {
            addCriterion("dis_city_midpointid is not null");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidEqualTo(String value) {
            addCriterion("dis_city_midpointid =", value, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidNotEqualTo(String value) {
            addCriterion("dis_city_midpointid <>", value, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidGreaterThan(String value) {
            addCriterion("dis_city_midpointid >", value, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidGreaterThanOrEqualTo(String value) {
            addCriterion("dis_city_midpointid >=", value, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidLessThan(String value) {
            addCriterion("dis_city_midpointid <", value, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidLessThanOrEqualTo(String value) {
            addCriterion("dis_city_midpointid <=", value, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidLike(String value) {
            addCriterion("dis_city_midpointid like", value, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidNotLike(String value) {
            addCriterion("dis_city_midpointid not like", value, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidIn(List<String> values) {
            addCriterion("dis_city_midpointid in", values, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidNotIn(List<String> values) {
            addCriterion("dis_city_midpointid not in", values, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidBetween(String value1, String value2) {
            addCriterion("dis_city_midpointid between", value1, value2, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andDisCityMidpointidNotBetween(String value1, String value2) {
            addCriterion("dis_city_midpointid not between", value1, value2, "disCityMidpointid");
            return (Criteria) this;
        }

        public Criteria andPEndidIsNull() {
            addCriterion("p_endid is null");
            return (Criteria) this;
        }

        public Criteria andPEndidIsNotNull() {
            addCriterion("p_endid is not null");
            return (Criteria) this;
        }

        public Criteria andPEndidEqualTo(String value) {
            addCriterion("p_endid =", value, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidNotEqualTo(String value) {
            addCriterion("p_endid <>", value, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidGreaterThan(String value) {
            addCriterion("p_endid >", value, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidGreaterThanOrEqualTo(String value) {
            addCriterion("p_endid >=", value, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidLessThan(String value) {
            addCriterion("p_endid <", value, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidLessThanOrEqualTo(String value) {
            addCriterion("p_endid <=", value, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidLike(String value) {
            addCriterion("p_endid like", value, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidNotLike(String value) {
            addCriterion("p_endid not like", value, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidIn(List<String> values) {
            addCriterion("p_endid in", values, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidNotIn(List<String> values) {
            addCriterion("p_endid not in", values, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidBetween(String value1, String value2) {
            addCriterion("p_endid between", value1, value2, "pEndid");
            return (Criteria) this;
        }

        public Criteria andPEndidNotBetween(String value1, String value2) {
            addCriterion("p_endid not between", value1, value2, "pEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidIsNull() {
            addCriterion("dis_city_endid is null");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidIsNotNull() {
            addCriterion("dis_city_endid is not null");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidEqualTo(String value) {
            addCriterion("dis_city_endid =", value, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidNotEqualTo(String value) {
            addCriterion("dis_city_endid <>", value, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidGreaterThan(String value) {
            addCriterion("dis_city_endid >", value, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidGreaterThanOrEqualTo(String value) {
            addCriterion("dis_city_endid >=", value, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidLessThan(String value) {
            addCriterion("dis_city_endid <", value, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidLessThanOrEqualTo(String value) {
            addCriterion("dis_city_endid <=", value, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidLike(String value) {
            addCriterion("dis_city_endid like", value, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidNotLike(String value) {
            addCriterion("dis_city_endid not like", value, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidIn(List<String> values) {
            addCriterion("dis_city_endid in", values, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidNotIn(List<String> values) {
            addCriterion("dis_city_endid not in", values, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidBetween(String value1, String value2) {
            addCriterion("dis_city_endid between", value1, value2, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andDisCityEndidNotBetween(String value1, String value2) {
            addCriterion("dis_city_endid not between", value1, value2, "disCityEndid");
            return (Criteria) this;
        }

        public Criteria andRPriceIsNull() {
            addCriterion("r_price is null");
            return (Criteria) this;
        }

        public Criteria andRPriceIsNotNull() {
            addCriterion("r_price is not null");
            return (Criteria) this;
        }

        public Criteria andRPriceEqualTo(Long value) {
            addCriterion("r_price =", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceNotEqualTo(Long value) {
            addCriterion("r_price <>", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceGreaterThan(Long value) {
            addCriterion("r_price >", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("r_price >=", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceLessThan(Long value) {
            addCriterion("r_price <", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceLessThanOrEqualTo(Long value) {
            addCriterion("r_price <=", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceIn(List<Long> values) {
            addCriterion("r_price in", values, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceNotIn(List<Long> values) {
            addCriterion("r_price not in", values, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceBetween(Long value1, Long value2) {
            addCriterion("r_price between", value1, value2, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceNotBetween(Long value1, Long value2) {
            addCriterion("r_price not between", value1, value2, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRRemarksIsNull() {
            addCriterion("r_remarks is null");
            return (Criteria) this;
        }

        public Criteria andRRemarksIsNotNull() {
            addCriterion("r_remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRRemarksEqualTo(String value) {
            addCriterion("r_remarks =", value, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksNotEqualTo(String value) {
            addCriterion("r_remarks <>", value, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksGreaterThan(String value) {
            addCriterion("r_remarks >", value, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("r_remarks >=", value, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksLessThan(String value) {
            addCriterion("r_remarks <", value, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksLessThanOrEqualTo(String value) {
            addCriterion("r_remarks <=", value, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksLike(String value) {
            addCriterion("r_remarks like", value, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksNotLike(String value) {
            addCriterion("r_remarks not like", value, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksIn(List<String> values) {
            addCriterion("r_remarks in", values, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksNotIn(List<String> values) {
            addCriterion("r_remarks not in", values, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksBetween(String value1, String value2) {
            addCriterion("r_remarks between", value1, value2, "rRemarks");
            return (Criteria) this;
        }

        public Criteria andRRemarksNotBetween(String value1, String value2) {
            addCriterion("r_remarks not between", value1, value2, "rRemarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_route
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}