package com.ojp.entity;

public class DisTributionscope {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionscope.ds_id
     *
     * @mbg.generated
     */
    private Integer dsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionscope.ds_name
     *
     * @mbg.generated
     */
    private String dsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionscope.ds_prices
     *
     * @mbg.generated
     */
    private Long dsPrices;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionscope.dis_city_id
     *
     * @mbg.generated
     */
    private String disCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionscope.ds_remarks
     *
     * @mbg.generated
     */
    private String dsRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionscope.ds_id
     *
     * @return the value of dis_tributionscope.ds_id
     *
     * @mbg.generated
     */
    public Integer getDsId() {
        return dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionscope.ds_id
     *
     * @param dsId the value for dis_tributionscope.ds_id
     *
     * @mbg.generated
     */
    public void setDsId(Integer dsId) {
        this.dsId = dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionscope.ds_name
     *
     * @return the value of dis_tributionscope.ds_name
     *
     * @mbg.generated
     */
    public String getDsName() {
        return dsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionscope.ds_name
     *
     * @param dsName the value for dis_tributionscope.ds_name
     *
     * @mbg.generated
     */
    public void setDsName(String dsName) {
        this.dsName = dsName == null ? null : dsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionscope.ds_prices
     *
     * @return the value of dis_tributionscope.ds_prices
     *
     * @mbg.generated
     */
    public Long getDsPrices() {
        return dsPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionscope.ds_prices
     *
     * @param dsPrices the value for dis_tributionscope.ds_prices
     *
     * @mbg.generated
     */
    public void setDsPrices(Long dsPrices) {
        this.dsPrices = dsPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionscope.dis_city_id
     *
     * @return the value of dis_tributionscope.dis_city_id
     *
     * @mbg.generated
     */
    public String getDisCityId() {
        return disCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionscope.dis_city_id
     *
     * @param disCityId the value for dis_tributionscope.dis_city_id
     *
     * @mbg.generated
     */
    public void setDisCityId(String disCityId) {
        this.disCityId = disCityId == null ? null : disCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionscope.ds_remarks
     *
     * @return the value of dis_tributionscope.ds_remarks
     *
     * @mbg.generated
     */
    public String getDsRemarks() {
        return dsRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionscope.ds_remarks
     *
     * @param dsRemarks the value for dis_tributionscope.ds_remarks
     *
     * @mbg.generated
     */
    public void setDsRemarks(String dsRemarks) {
        this.dsRemarks = dsRemarks == null ? null : dsRemarks.trim();
    }
}