package com.ojp.entity;

public class DisTributionpoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionpoint.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionpoint.d_name
     *
     * @mbg.generated
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionpoint.p_id
     *
     * @mbg.generated
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionpoint.dis_city_id
     *
     * @mbg.generated
     */
    private String disCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionpoint.a_id
     *
     * @mbg.generated
     */
    private String aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionpoint.d_phone
     *
     * @mbg.generated
     */
    private String dPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionpoint.d_prices
     *
     * @mbg.generated
     */
    private String dPrices;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_tributionpoint.d_remarks
     *
     * @mbg.generated
     */
    private String dRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionpoint.d_id
     *
     * @return the value of dis_tributionpoint.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionpoint.d_id
     *
     * @param dId the value for dis_tributionpoint.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionpoint.d_name
     *
     * @return the value of dis_tributionpoint.d_name
     *
     * @mbg.generated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionpoint.d_name
     *
     * @param dName the value for dis_tributionpoint.d_name
     *
     * @mbg.generated
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionpoint.p_id
     *
     * @return the value of dis_tributionpoint.p_id
     *
     * @mbg.generated
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionpoint.p_id
     *
     * @param pId the value for dis_tributionpoint.p_id
     *
     * @mbg.generated
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionpoint.dis_city_id
     *
     * @return the value of dis_tributionpoint.dis_city_id
     *
     * @mbg.generated
     */
    public String getDisCityId() {
        return disCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionpoint.dis_city_id
     *
     * @param disCityId the value for dis_tributionpoint.dis_city_id
     *
     * @mbg.generated
     */
    public void setDisCityId(String disCityId) {
        this.disCityId = disCityId == null ? null : disCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionpoint.a_id
     *
     * @return the value of dis_tributionpoint.a_id
     *
     * @mbg.generated
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionpoint.a_id
     *
     * @param aId the value for dis_tributionpoint.a_id
     *
     * @mbg.generated
     */
    public void setaId(String aId) {
        this.aId = aId == null ? null : aId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionpoint.d_phone
     *
     * @return the value of dis_tributionpoint.d_phone
     *
     * @mbg.generated
     */
    public String getdPhone() {
        return dPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionpoint.d_phone
     *
     * @param dPhone the value for dis_tributionpoint.d_phone
     *
     * @mbg.generated
     */
    public void setdPhone(String dPhone) {
        this.dPhone = dPhone == null ? null : dPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionpoint.d_prices
     *
     * @return the value of dis_tributionpoint.d_prices
     *
     * @mbg.generated
     */
    public String getdPrices() {
        return dPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionpoint.d_prices
     *
     * @param dPrices the value for dis_tributionpoint.d_prices
     *
     * @mbg.generated
     */
    public void setdPrices(String dPrices) {
        this.dPrices = dPrices == null ? null : dPrices.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_tributionpoint.d_remarks
     *
     * @return the value of dis_tributionpoint.d_remarks
     *
     * @mbg.generated
     */
    public String getdRemarks() {
        return dRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_tributionpoint.d_remarks
     *
     * @param dRemarks the value for dis_tributionpoint.d_remarks
     *
     * @mbg.generated
     */
    public void setdRemarks(String dRemarks) {
        this.dRemarks = dRemarks == null ? null : dRemarks.trim();
    }
}