package com.ojp.entity;

public class DisUsergroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_usergroup.u_number
     *
     * @mbg.generated
     */
    private String uNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_usergroup.u_name
     *
     * @mbg.generated
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_usergroup.u_remarks
     *
     * @mbg.generated
     */
    private String uRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_usergroup.u_number
     *
     * @return the value of dis_usergroup.u_number
     *
     * @mbg.generated
     */
    public String getuNumber() {
        return uNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_usergroup.u_number
     *
     * @param uNumber the value for dis_usergroup.u_number
     *
     * @mbg.generated
     */
    public void setuNumber(String uNumber) {
        this.uNumber = uNumber == null ? null : uNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_usergroup.u_name
     *
     * @return the value of dis_usergroup.u_name
     *
     * @mbg.generated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_usergroup.u_name
     *
     * @param uName the value for dis_usergroup.u_name
     *
     * @mbg.generated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_usergroup.u_remarks
     *
     * @return the value of dis_usergroup.u_remarks
     *
     * @mbg.generated
     */
    public String getuRemarks() {
        return uRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_usergroup.u_remarks
     *
     * @param uRemarks the value for dis_usergroup.u_remarks
     *
     * @mbg.generated
     */
    public void setuRemarks(String uRemarks) {
        this.uRemarks = uRemarks == null ? null : uRemarks.trim();
    }
}