package com.ojp.entity;

import java.util.Date;

public class DisVehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_vehicle.v_id
     *
     * @mbg.generated
     */
    private String vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_vehicle.v_productionaddress
     *
     * @mbg.generated
     */
    private String vProductionaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_vehicle.v_model
     *
     * @mbg.generated
     */
    private String vModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_vehicle.v_dis_routenuber
     *
     * @mbg.generated
     */
    private String vDisRoutenuber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_vehicle.v_productionday
     *
     * @mbg.generated
     */
    private Date vProductionday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_vehicle.v_purchaseday
     *
     * @mbg.generated
     */
    private Date vPurchaseday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_vehicle.v_remarks
     *
     * @mbg.generated
     */
    private String vRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_vehicle.v_id
     *
     * @return the value of dis_vehicle.v_id
     *
     * @mbg.generated
     */
    public String getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_vehicle.v_id
     *
     * @param vId the value for dis_vehicle.v_id
     *
     * @mbg.generated
     */
    public void setvId(String vId) {
        this.vId = vId == null ? null : vId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_vehicle.v_productionaddress
     *
     * @return the value of dis_vehicle.v_productionaddress
     *
     * @mbg.generated
     */
    public String getvProductionaddress() {
        return vProductionaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_vehicle.v_productionaddress
     *
     * @param vProductionaddress the value for dis_vehicle.v_productionaddress
     *
     * @mbg.generated
     */
    public void setvProductionaddress(String vProductionaddress) {
        this.vProductionaddress = vProductionaddress == null ? null : vProductionaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_vehicle.v_model
     *
     * @return the value of dis_vehicle.v_model
     *
     * @mbg.generated
     */
    public String getvModel() {
        return vModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_vehicle.v_model
     *
     * @param vModel the value for dis_vehicle.v_model
     *
     * @mbg.generated
     */
    public void setvModel(String vModel) {
        this.vModel = vModel == null ? null : vModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_vehicle.v_dis_routenuber
     *
     * @return the value of dis_vehicle.v_dis_routenuber
     *
     * @mbg.generated
     */
    public String getvDisRoutenuber() {
        return vDisRoutenuber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_vehicle.v_dis_routenuber
     *
     * @param vDisRoutenuber the value for dis_vehicle.v_dis_routenuber
     *
     * @mbg.generated
     */
    public void setvDisRoutenuber(String vDisRoutenuber) {
        this.vDisRoutenuber = vDisRoutenuber == null ? null : vDisRoutenuber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_vehicle.v_productionday
     *
     * @return the value of dis_vehicle.v_productionday
     *
     * @mbg.generated
     */
    public Date getvProductionday() {
        return vProductionday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_vehicle.v_productionday
     *
     * @param vProductionday the value for dis_vehicle.v_productionday
     *
     * @mbg.generated
     */
    public void setvProductionday(Date vProductionday) {
        this.vProductionday = vProductionday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_vehicle.v_purchaseday
     *
     * @return the value of dis_vehicle.v_purchaseday
     *
     * @mbg.generated
     */
    public Date getvPurchaseday() {
        return vPurchaseday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_vehicle.v_purchaseday
     *
     * @param vPurchaseday the value for dis_vehicle.v_purchaseday
     *
     * @mbg.generated
     */
    public void setvPurchaseday(Date vPurchaseday) {
        this.vPurchaseday = vPurchaseday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_vehicle.v_remarks
     *
     * @return the value of dis_vehicle.v_remarks
     *
     * @mbg.generated
     */
    public String getvRemarks() {
        return vRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_vehicle.v_remarks
     *
     * @param vRemarks the value for dis_vehicle.v_remarks
     *
     * @mbg.generated
     */
    public void setvRemarks(String vRemarks) {
        this.vRemarks = vRemarks == null ? null : vRemarks.trim();
    }
}