package com.ojp.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DisVehicleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public DisVehicleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVIdIsNull() {
            addCriterion("v_id is null");
            return (Criteria) this;
        }

        public Criteria andVIdIsNotNull() {
            addCriterion("v_id is not null");
            return (Criteria) this;
        }

        public Criteria andVIdEqualTo(String value) {
            addCriterion("v_id =", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotEqualTo(String value) {
            addCriterion("v_id <>", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdGreaterThan(String value) {
            addCriterion("v_id >", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdGreaterThanOrEqualTo(String value) {
            addCriterion("v_id >=", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdLessThan(String value) {
            addCriterion("v_id <", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdLessThanOrEqualTo(String value) {
            addCriterion("v_id <=", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdLike(String value) {
            addCriterion("v_id like", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotLike(String value) {
            addCriterion("v_id not like", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdIn(List<String> values) {
            addCriterion("v_id in", values, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotIn(List<String> values) {
            addCriterion("v_id not in", values, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdBetween(String value1, String value2) {
            addCriterion("v_id between", value1, value2, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotBetween(String value1, String value2) {
            addCriterion("v_id not between", value1, value2, "vId");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressIsNull() {
            addCriterion("v_productionaddress is null");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressIsNotNull() {
            addCriterion("v_productionaddress is not null");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressEqualTo(String value) {
            addCriterion("v_productionaddress =", value, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressNotEqualTo(String value) {
            addCriterion("v_productionaddress <>", value, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressGreaterThan(String value) {
            addCriterion("v_productionaddress >", value, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressGreaterThanOrEqualTo(String value) {
            addCriterion("v_productionaddress >=", value, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressLessThan(String value) {
            addCriterion("v_productionaddress <", value, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressLessThanOrEqualTo(String value) {
            addCriterion("v_productionaddress <=", value, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressLike(String value) {
            addCriterion("v_productionaddress like", value, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressNotLike(String value) {
            addCriterion("v_productionaddress not like", value, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressIn(List<String> values) {
            addCriterion("v_productionaddress in", values, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressNotIn(List<String> values) {
            addCriterion("v_productionaddress not in", values, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressBetween(String value1, String value2) {
            addCriterion("v_productionaddress between", value1, value2, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVProductionaddressNotBetween(String value1, String value2) {
            addCriterion("v_productionaddress not between", value1, value2, "vProductionaddress");
            return (Criteria) this;
        }

        public Criteria andVModelIsNull() {
            addCriterion("v_model is null");
            return (Criteria) this;
        }

        public Criteria andVModelIsNotNull() {
            addCriterion("v_model is not null");
            return (Criteria) this;
        }

        public Criteria andVModelEqualTo(String value) {
            addCriterion("v_model =", value, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelNotEqualTo(String value) {
            addCriterion("v_model <>", value, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelGreaterThan(String value) {
            addCriterion("v_model >", value, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelGreaterThanOrEqualTo(String value) {
            addCriterion("v_model >=", value, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelLessThan(String value) {
            addCriterion("v_model <", value, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelLessThanOrEqualTo(String value) {
            addCriterion("v_model <=", value, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelLike(String value) {
            addCriterion("v_model like", value, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelNotLike(String value) {
            addCriterion("v_model not like", value, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelIn(List<String> values) {
            addCriterion("v_model in", values, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelNotIn(List<String> values) {
            addCriterion("v_model not in", values, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelBetween(String value1, String value2) {
            addCriterion("v_model between", value1, value2, "vModel");
            return (Criteria) this;
        }

        public Criteria andVModelNotBetween(String value1, String value2) {
            addCriterion("v_model not between", value1, value2, "vModel");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberIsNull() {
            addCriterion("v_dis_routenuber is null");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberIsNotNull() {
            addCriterion("v_dis_routenuber is not null");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberEqualTo(String value) {
            addCriterion("v_dis_routenuber =", value, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberNotEqualTo(String value) {
            addCriterion("v_dis_routenuber <>", value, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberGreaterThan(String value) {
            addCriterion("v_dis_routenuber >", value, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberGreaterThanOrEqualTo(String value) {
            addCriterion("v_dis_routenuber >=", value, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberLessThan(String value) {
            addCriterion("v_dis_routenuber <", value, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberLessThanOrEqualTo(String value) {
            addCriterion("v_dis_routenuber <=", value, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberLike(String value) {
            addCriterion("v_dis_routenuber like", value, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberNotLike(String value) {
            addCriterion("v_dis_routenuber not like", value, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberIn(List<String> values) {
            addCriterion("v_dis_routenuber in", values, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberNotIn(List<String> values) {
            addCriterion("v_dis_routenuber not in", values, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberBetween(String value1, String value2) {
            addCriterion("v_dis_routenuber between", value1, value2, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVDisRoutenuberNotBetween(String value1, String value2) {
            addCriterion("v_dis_routenuber not between", value1, value2, "vDisRoutenuber");
            return (Criteria) this;
        }

        public Criteria andVProductiondayIsNull() {
            addCriterion("v_productionday is null");
            return (Criteria) this;
        }

        public Criteria andVProductiondayIsNotNull() {
            addCriterion("v_productionday is not null");
            return (Criteria) this;
        }

        public Criteria andVProductiondayEqualTo(Date value) {
            addCriterion("v_productionday =", value, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVProductiondayNotEqualTo(Date value) {
            addCriterion("v_productionday <>", value, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVProductiondayGreaterThan(Date value) {
            addCriterion("v_productionday >", value, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVProductiondayGreaterThanOrEqualTo(Date value) {
            addCriterion("v_productionday >=", value, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVProductiondayLessThan(Date value) {
            addCriterion("v_productionday <", value, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVProductiondayLessThanOrEqualTo(Date value) {
            addCriterion("v_productionday <=", value, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVProductiondayIn(List<Date> values) {
            addCriterion("v_productionday in", values, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVProductiondayNotIn(List<Date> values) {
            addCriterion("v_productionday not in", values, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVProductiondayBetween(Date value1, Date value2) {
            addCriterion("v_productionday between", value1, value2, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVProductiondayNotBetween(Date value1, Date value2) {
            addCriterion("v_productionday not between", value1, value2, "vProductionday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayIsNull() {
            addCriterion("v_purchaseday is null");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayIsNotNull() {
            addCriterion("v_purchaseday is not null");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayEqualTo(Date value) {
            addCriterion("v_purchaseday =", value, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayNotEqualTo(Date value) {
            addCriterion("v_purchaseday <>", value, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayGreaterThan(Date value) {
            addCriterion("v_purchaseday >", value, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayGreaterThanOrEqualTo(Date value) {
            addCriterion("v_purchaseday >=", value, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayLessThan(Date value) {
            addCriterion("v_purchaseday <", value, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayLessThanOrEqualTo(Date value) {
            addCriterion("v_purchaseday <=", value, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayIn(List<Date> values) {
            addCriterion("v_purchaseday in", values, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayNotIn(List<Date> values) {
            addCriterion("v_purchaseday not in", values, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayBetween(Date value1, Date value2) {
            addCriterion("v_purchaseday between", value1, value2, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVPurchasedayNotBetween(Date value1, Date value2) {
            addCriterion("v_purchaseday not between", value1, value2, "vPurchaseday");
            return (Criteria) this;
        }

        public Criteria andVRemarksIsNull() {
            addCriterion("v_remarks is null");
            return (Criteria) this;
        }

        public Criteria andVRemarksIsNotNull() {
            addCriterion("v_remarks is not null");
            return (Criteria) this;
        }

        public Criteria andVRemarksEqualTo(String value) {
            addCriterion("v_remarks =", value, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksNotEqualTo(String value) {
            addCriterion("v_remarks <>", value, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksGreaterThan(String value) {
            addCriterion("v_remarks >", value, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("v_remarks >=", value, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksLessThan(String value) {
            addCriterion("v_remarks <", value, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksLessThanOrEqualTo(String value) {
            addCriterion("v_remarks <=", value, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksLike(String value) {
            addCriterion("v_remarks like", value, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksNotLike(String value) {
            addCriterion("v_remarks not like", value, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksIn(List<String> values) {
            addCriterion("v_remarks in", values, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksNotIn(List<String> values) {
            addCriterion("v_remarks not in", values, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksBetween(String value1, String value2) {
            addCriterion("v_remarks between", value1, value2, "vRemarks");
            return (Criteria) this;
        }

        public Criteria andVRemarksNotBetween(String value1, String value2) {
            addCriterion("v_remarks not between", value1, value2, "vRemarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_vehicle
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}