package com.ojp.dao;

import com.ojp.entity.DisAdministrators;
import com.ojp.entity.DisAdministratorsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisAdministratorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    long countByExample(DisAdministratorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    int deleteByExample(DisAdministratorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    int insert(DisAdministrators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    int insertSelective(DisAdministrators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    List<DisAdministrators> selectByExample(DisAdministratorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    DisAdministrators selectByPrimaryKey(String aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisAdministrators record, @Param("example") DisAdministratorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisAdministrators record, @Param("example") DisAdministratorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisAdministrators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_administrators
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisAdministrators record);
}