package com.ojp.dao;

import com.ojp.entity.DisCityregion;
import com.ojp.entity.DisCityregionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisCityregionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    long countByExample(DisCityregionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    int deleteByExample(DisCityregionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    int insert(DisCityregion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    int insertSelective(DisCityregion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    List<DisCityregion> selectByExample(DisCityregionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    DisCityregion selectByPrimaryKey(String cgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisCityregion record, @Param("example") DisCityregionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisCityregion record, @Param("example") DisCityregionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisCityregion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_cityregion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisCityregion record);
}