package com.ojp.dao;

import com.ojp.entity.DisCity;
import com.ojp.entity.DisCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    long countByExample(DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int deleteByExample(DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String disCityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int insert(DisCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int insertSelective(DisCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    List<DisCity> selectByExample(DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    DisCity selectByPrimaryKey(String disCityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisCity record, @Param("example") DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisCity record, @Param("example") DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisCity record);
}