package com.ojp.dao;

import com.ojp.entity.DisOrders;
import com.ojp.entity.DisOrdersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    long countByExample(DisOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    int deleteByExample(DisOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    int insert(DisOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    int insertSelective(DisOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    List<DisOrders> selectByExample(DisOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    DisOrders selectByPrimaryKey(String oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisOrders record, @Param("example") DisOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisOrders record, @Param("example") DisOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisOrders record);
}