package com.ojp.dao;

import com.ojp.entity.DisRoute;
import com.ojp.entity.DisRouteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    long countByExample(DisRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    int deleteByExample(DisRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    int insert(DisRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    int insertSelective(DisRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    List<DisRoute> selectByExample(DisRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    DisRoute selectByPrimaryKey(String rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisRoute record, @Param("example") DisRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisRoute record, @Param("example") DisRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_route
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisRoute record);
}