package com.ojp.dao;

import com.ojp.entity.DisTributionpoint;
import com.ojp.entity.DisTributionpointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisTributionpointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    long countByExample(DisTributionpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    int deleteByExample(DisTributionpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    int insert(DisTributionpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    int insertSelective(DisTributionpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    List<DisTributionpoint> selectByExample(DisTributionpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    DisTributionpoint selectByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisTributionpoint record, @Param("example") DisTributionpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisTributionpoint record, @Param("example") DisTributionpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisTributionpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionpoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisTributionpoint record);
}