package com.ojp.dao;

import com.ojp.entity.DisTributionscope;
import com.ojp.entity.DisTributionscopeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisTributionscopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    long countByExample(DisTributionscopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    int deleteByExample(DisTributionscopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    int insert(DisTributionscope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    int insertSelective(DisTributionscope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    List<DisTributionscope> selectByExample(DisTributionscopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    DisTributionscope selectByPrimaryKey(Integer dsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisTributionscope record, @Param("example") DisTributionscopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisTributionscope record, @Param("example") DisTributionscopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisTributionscope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_tributionscope
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisTributionscope record);
}