package com.ojp.dao;

import com.ojp.entity.DisUsergroup;
import com.ojp.entity.DisUsergroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisUsergroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    long countByExample(DisUsergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    int deleteByExample(DisUsergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    int insert(DisUsergroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    int insertSelective(DisUsergroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    List<DisUsergroup> selectByExample(DisUsergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    DisUsergroup selectByPrimaryKey(String uNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisUsergroup record, @Param("example") DisUsergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisUsergroup record, @Param("example") DisUsergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisUsergroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_usergroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisUsergroup record);
}