package com.ojp.dao;

import com.ojp.entity.DisVehicle;
import com.ojp.entity.DisVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    long countByExample(DisVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    int deleteByExample(DisVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    int insert(DisVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    int insertSelective(DisVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    List<DisVehicle> selectByExample(DisVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    DisVehicle selectByPrimaryKey(String vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisVehicle record, @Param("example") DisVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisVehicle record, @Param("example") DisVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisVehicle record);
}